In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
#Load the MovieLens 1M movie dataset 

movies_1M = pd.read_table('movies.dat',sep='::',names=['movieid','title','genre'], engine='python')

In [4]:
len(movies_1M)

3883

In [5]:
movies_1M.to_csv('movies_1M.csv')

In [6]:
movies_1M

,movieid,title,genre
0,1,Toy Story (1995),Animation|Children's|Comedy
1,2,Jumanji (1995),Adventure|Children's|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama
4,5,Father of the Bride Part II (1995),Comedy
5,6,Heat (1995),Action|Crime|Thriller
6,7,Sabrina (1995),Comedy|Romance
7,8,Tom and Huck (1995),Adventure|Children's
8,9,Sudden Death (1995),Action
9,10,GoldenEye (1995),Action|Adventure|Thriller
10,11,"American President, The (1995)",Comedy|Drama|Romance
11,12,Dracula: Dead and Loving It (1995),Comedy|Horror
12,13,Balto (1995),Animation|Children's
13,14,Nixon (1995),Drama
14,15,Cutthroat Island (1995),Action|Adventure|Romance
15,16,Casino (1995),Drama|Thriller
16,17,Sense and Sensibility (1995),Drama|Romance
17,18,Four Rooms (1995),Thriller
18,19,Ace Ventura: When Nature Calls (1995),Comedy
19,20,Money Train (1995),Action
20,21,Get Shorty (1995),Action|Comedy|Drama
21,22,Copycat (1995),Crime|Drama|Thriller
22,23,Assassins (1995),Thriller
23,24,Powder (1995),Drama|Sci-Fi
24,25,Leaving Las Vegas (1995),Drama|Romance
25,26,Othello (1995),Drama
26,27,Now and Then (1995),Drama
27,28,Persuasion (1995),Romance
28,29,"City of Lost Children, The (1995)",Adventure|Sci-Fi
29,30,Shanghai Triad (Yao a yao yao dao waipo qiao) ...,Drama
...,...,...,...
3853,3923,Return of the Fly (1959),Horror|Sci-Fi
3854,3924,Pajama Party (1964),Comedy
3855,3925,Stranger Than Paradise (1984),Comedy
3856,3926,Voyage to the Bottom of the Sea (1961),Adventure|Sci-Fi
3857,3927,Fantastic Voyage (1966),Adventure|Sci-Fi
3858,3928,Abbott and Costello Meet Frankenstein (1948),Comedy|Horror
3859,3929,"Bank Dick, The (1940)",Comedy
3860,3930,"Creature From the Black Lagoon, The (1954)",Horror
3861,3931,"Giant Gila Monster, The (1959)",Horror|Sci-Fi
3862,3932,"Invisible Man, The (1933)",Horror|Sci-Fi
3863,3933,"Killer Shrews, The (1959)",Horror|Sci-Fi
3864,3934,Kronos (1957),Sci-Fi
3865,3935,Kronos (1973),Horror
3866,3936,"Phantom of the Opera, The (1943)",Drama|Thriller
3867,3937,Runaway (1984),Sci-Fi|Thriller
3868,3938,"Slumber Party Massacre, The (1982)",Horror
3869,3939,"Slumber Party Massacre II, The (1987)",Horror
3870,3940,"Slumber Party Massacre III, The (1990)",Horror
3871,3941,Sorority House Massacre (1986),Horror
3872,3942,Sorority House Massacre II (1990),Horror
3873,3943,Bamboozled (2000),Comedy
3874,3944,Bootmen (2000),Comedy|Drama
3875,3945,Digimon: The Movie (2000),Adventure|Animation|Children's
3876,3946,Get Carter (2000),Action|Drama|Thriller
3877,3947,Get Carter (1971),Thriller
3878,3948,Meet the Parents (2000),Comedy
3879,3949,Requiem for a Dream (2000),Drama
3880,3950,Tigerland (2000),Drama
3881,3951,Two Family House (2000),Drama
3882,3952,"Contender, The (2000)",Drama|Thriller

In [7]:
#Load the links data from MovieLens 20M movie dataset 

links_20M = pd.read_csv('links_20M.csv')

In [8]:
links_20M

       movieid   imdbId
0            1   114709
1            2   113497
2            3   113228
3            4   114885
4            5   113041
5            6   113277
6            7   114319
7            8   112302
8            9   114576
9           10   113189
10          11   112346
11          12   112896
12          13   112453
13          14   113987
14          15   112760
15          16   112641
16          17   114388
17          18   113101
18          19   112281
19          20   113845
20          21   113161
21          22   112722
22          23   112401
23          24   114168
24          25   113627
25          26   114057
26          27   114011
27          28   114117
28          29   112682
29          30   115012
...        ...      ...
27248   131146   184005
27249   131148  1661461
27250   131150   461642
27251   131152    59171
27252   131154   202806
27253   131156   295375
27254   131158   102397
27255   131160  1242522
27256   131162  3028412
27257   131164  2109059
27258   131166  1489097
27259   131168  2764784
27260   131170  3479316
27261   131172  2626926
27262   131174  2058617
27263   131176  3305316
27264   131180  3816458
27265   131231  1645916
27266   131237  1595366
27267   131239  1747994
27268   131241   239450
27269   131243   304931
27270   131248   465925
27271   131250   248409
27272   131252   289477
27273   131254   466713
27274   131256   277703
27275   131258  3485166
27276   131260   249110
27277   131262  1724965

[27278 rows x 2 columns]

In [12]:
movielens_1M_final = pd.merge (movies_1M, links_20M, on='movieid')

In [14]:
len(movielens_1M_final)

3859

In [13]:
#Final Movielens 1M Dataset with 3859 movies along with their IMDB links.

movielens_1M_final

,movieid,title,genre,imdbId
0,1,Toy Story (1995),Animation|Children's|Comedy,114709
1,2,Jumanji (1995),Adventure|Children's|Fantasy,113497
2,3,Grumpier Old Men (1995),Comedy|Romance,113228
3,4,Waiting to Exhale (1995),Comedy|Drama,114885
4,5,Father of the Bride Part II (1995),Comedy,113041
5,6,Heat (1995),Action|Crime|Thriller,113277
6,7,Sabrina (1995),Comedy|Romance,114319
7,8,Tom and Huck (1995),Adventure|Children's,112302
8,9,Sudden Death (1995),Action,114576
9,10,GoldenEye (1995),Action|Adventure|Thriller,113189
10,11,"American President, The (1995)",Comedy|Drama|Romance,112346
11,12,Dracula: Dead and Loving It (1995),Comedy|Horror,112896
12,13,Balto (1995),Animation|Children's,112453
13,14,Nixon (1995),Drama,113987
14,15,Cutthroat Island (1995),Action|Adventure|Romance,112760
15,16,Casino (1995),Drama|Thriller,112641
16,17,Sense and Sensibility (1995),Drama|Romance,114388
17,18,Four Rooms (1995),Thriller,113101
18,19,Ace Ventura: When Nature Calls (1995),Comedy,112281
19,20,Money Train (1995),Action,113845
20,21,Get Shorty (1995),Action|Comedy|Drama,113161
21,22,Copycat (1995),Crime|Drama|Thriller,112722
22,23,Assassins (1995),Thriller,112401
23,24,Powder (1995),Drama|Sci-Fi,114168
24,25,Leaving Las Vegas (1995),Drama|Romance,113627
25,26,Othello (1995),Drama,114057
26,27,Now and Then (1995),Drama,114011
27,28,Persuasion (1995),Romance,114117
28,29,"City of Lost Children, The (1995)",Adventure|Sci-Fi,112682
29,30,Shanghai Triad (Yao a yao yao dao waipo qiao) ...,Drama,115012
...,...,...,...,...
3829,3922,Bikini Beach (1964),Comedy,57887
3830,3923,Return of the Fly (1959),Horror|Sci-Fi,53219
3831,3924,Pajama Party (1964),Comedy,58440
3832,3925,Stranger Than Paradise (1984),Comedy,88184
3833,3926,Voyage to the Bottom of the Sea (1961),Adventure|Sci-Fi,55608
3834,3927,Fantastic Voyage (1966),Adventure|Sci-Fi,60397
3835,3928,Abbott and Costello Meet Frankenstein (1948),Comedy|Horror,40068
3836,3929,"Bank Dick, The (1940)",Comedy,32234
3837,3930,"Creature From the Black Lagoon, The (1954)",Horror,46876
3838,3931,"Giant Gila Monster, The (1959)",Horror|Sci-Fi,52846
3839,3932,"Invisible Man, The (1933)",Horror|Sci-Fi,24184
3840,3933,"Killer Shrews, The (1959)",Horror|Sci-Fi,52969
3841,3934,Kronos (1957),Sci-Fi,50610
3842,3936,"Phantom of the Opera, The (1943)",Drama|Thriller,36261
3843,3937,Runaway (1984),Sci-Fi|Thriller,88024
3844,3938,"Slumber Party Massacre, The (1982)",Horror,84695
3845,3939,"Slumber Party Massacre II, The (1987)",Horror,93996
3846,3940,"Slumber Party Massacre III, The (1990)",Horror,100639
3847,3941,Sorority House Massacre (1986),Horror,91990
3848,3942,Sorority House Massacre II (1990),Horror,100663
3849,3943,Bamboozled (2000),Comedy,215545
3850,3944,Bootmen (2000),Comedy|Drama,210584
3851,3945,Digimon: The Movie (2000),Adventure|Animation|Children's,259974
3852,3946,Get Carter (2000),Action|Drama|Thriller,208988
3853,3947,Get Carter (1971),Thriller,67128
3854,3948,Meet the Parents (2000),Comedy,212338
3855,3949,Requiem for a Dream (2000),Drama,180093
3856,3950,Tigerland (2000),Drama,170691
3857,3951,Two Family House (2000),Drama,202641
3858,3952,"Contender, The (2000)",Drama|Thriller,208874

In [15]:
#Load the MovieTweetings movie dataset 

movies_MT = pd.read_table('movies_MT.dat',sep='::',names=['imdbId','title','genre'], engine='python')

In [16]:
movies_MT

,imdbId,title,genre
0,8,Edison Kinetoscopic Record of a Sneeze (1894),Documentary|Short
1,10,La sortie des usines Lumière (1895),Documentary|Short
2,12,The Arrival of a Train (1896),Documentary|Short
3,25,The Oxford and Cambridge University Boat Race ...,NaN
4,91,Le manoir du diable (1896),Short|Horror
5,417,Le voyage dans la lune (1902),Short|Adventure|Fantasy
6,439,The Great Train Robbery (1903),Short|Action|Crime
7,443,"Hiawatha, the Messiah of the Ojibway (1903)",NaN
8,628,The Adventures of Dollie (1908),Action|Short
9,833,The Country Doctor (1909),Short|Drama
10,1223,Frankenstein (1910),Short|Fantasy|Horror
11,1740,The Lonedale Operator (1911),Short|Drama|Romance
12,2101,Cleopatra (1912),Drama|History
13,2130,L'inferno (1911),Adventure|Drama|Fantasy
14,2354,Max et Jane veulent faire du théâtre (1911),Short|Comedy
15,2844,Fantômas - À l'ombre de la guillotine (1913),Crime|Drama
16,3740,Cabiria (1914),Adventure|Drama|History
17,3863,Dough and Dynamite (1914),Comedy|Short
18,4099,"His Majesty, the Scarecrow of Oz (1914)",Family|Fantasy|Adventure
19,4100,His Musical Career (1914),Short|Comedy
20,4101,His New Profession (1914),Short|Comedy
21,4210,Laughing Gas (1914),Short|Comedy
22,4395,The New Janitor (1914),Short|Comedy
23,4457,The Patchwork Girl of Oz (1914),Adventure|Family|Fantasy
24,4518,Recreation (1914),Comedy|Short
25,4546,The Rounders (1914),Comedy|Short
26,4936,The Bank (1915),Comedy|Short
27,4972,The Birth of a Nation (1915),Drama|History|War
28,5074,The Champion (1915),Short|Comedy|Sport
29,5078,The Cheat (1915),Drama
...,...,...,...
30562,7746238,Chrisye (2017),NaN
30563,7752054,Katt Williams: Great America (2018),NaN
30564,7752142,Todd Glass: Act Happy (2018),NaN
30565,7761204,WWE Royal Rumble (2018),NaN
30566,7763020,Dovlatov (2018),NaN
30567,7768848,Wild Wild Country (2018),NaN
30568,7807486,UFC 220: Miocic vs. Ngannou (2018),NaN
30569,7830574,Ricky Gervais: Humanity (2018),NaN
30570,7833952,Talq Senaee (2018),NaN
30571,7843946,Dilan 1990 (2018),NaN
30572,7853242,Love Per Square Foot (2018),NaN
30573,7865404,Yo! My Saint (2018),NaN
30574,7871636,Deliha 2 (2018),NaN
30575,7882406,Dört Köse (2017),NaN
30576,7888178,Jar of Ashes (2018),NaN
30577,7917456,Slightly Off (2018),NaN
30578,7923374,Badang (2018),NaN
30579,7923890,Justin Timberlake: Say Something (2018),NaN
30580,7924798,Fred Armisen: Standup For Drummers (2018),NaN
30581,7924808,Derren Brown: The Push (2018),NaN
30582,7924820,The Trader (2018),NaN
30583,7942708,KL Special Force (2018),NaN
30584,7959216,Utøya 22. juli (2018),NaN
30585,7967954,Lee Chong Wei (2018),NaN
30586,7983844,Take Your Pills (2018),NaN
30587,8005338,Chris Rock: Tamborine (2018),NaN
30588,8043254,Sirb al-Hamam (2018),NaN
30589,8080268,Rock 'n' Roll Guns for Hire: The Story of the ...,NaN
30590,8080556,The Director and The Jedi (2018),NaN
30591,8088944,Ban-deu-si Jab-neun-da (2017),NaN

In [17]:
#Should have 7 characters in the imdbId field in Movielens Dataset

movielens_1M_final['imdbId'] = movielens_1M_final['imdbId'].apply(lambda x: '{0:0>7}'.format(x))

In [18]:
movielens_1M_final

,movieid,title,genre,imdbId
0,1,Toy Story (1995),Animation|Children's|Comedy,0114709
1,2,Jumanji (1995),Adventure|Children's|Fantasy,0113497
2,3,Grumpier Old Men (1995),Comedy|Romance,0113228
3,4,Waiting to Exhale (1995),Comedy|Drama,0114885
4,5,Father of the Bride Part II (1995),Comedy,0113041
5,6,Heat (1995),Action|Crime|Thriller,0113277
6,7,Sabrina (1995),Comedy|Romance,0114319
7,8,Tom and Huck (1995),Adventure|Children's,0112302
8,9,Sudden Death (1995),Action,0114576
9,10,GoldenEye (1995),Action|Adventure|Thriller,0113189
10,11,"American President, The (1995)",Comedy|Drama|Romance,0112346
11,12,Dracula: Dead and Loving It (1995),Comedy|Horror,0112896
12,13,Balto (1995),Animation|Children's,0112453
13,14,Nixon (1995),Drama,0113987
14,15,Cutthroat Island (1995),Action|Adventure|Romance,0112760
15,16,Casino (1995),Drama|Thriller,0112641
16,17,Sense and Sensibility (1995),Drama|Romance,0114388
17,18,Four Rooms (1995),Thriller,0113101
18,19,Ace Ventura: When Nature Calls (1995),Comedy,0112281
19,20,Money Train (1995),Action,0113845
20,21,Get Shorty (1995),Action|Comedy|Drama,0113161
21,22,Copycat (1995),Crime|Drama|Thriller,0112722
22,23,Assassins (1995),Thriller,0112401
23,24,Powder (1995),Drama|Sci-Fi,0114168
24,25,Leaving Las Vegas (1995),Drama|Romance,0113627
25,26,Othello (1995),Drama,0114057
26,27,Now and Then (1995),Drama,0114011
27,28,Persuasion (1995),Romance,0114117
28,29,"City of Lost Children, The (1995)",Adventure|Sci-Fi,0112682
29,30,Shanghai Triad (Yao a yao yao dao waipo qiao) ...,Drama,0115012
...,...,...,...,...
3829,3922,Bikini Beach (1964),Comedy,0057887
3830,3923,Return of the Fly (1959),Horror|Sci-Fi,0053219
3831,3924,Pajama Party (1964),Comedy,0058440
3832,3925,Stranger Than Paradise (1984),Comedy,0088184
3833,3926,Voyage to the Bottom of the Sea (1961),Adventure|Sci-Fi,0055608
3834,3927,Fantastic Voyage (1966),Adventure|Sci-Fi,0060397
3835,3928,Abbott and Costello Meet Frankenstein (1948),Comedy|Horror,0040068
3836,3929,"Bank Dick, The (1940)",Comedy,0032234
3837,3930,"Creature From the Black Lagoon, The (1954)",Horror,0046876
3838,3931,"Giant Gila Monster, The (1959)",Horror|Sci-Fi,0052846
3839,3932,"Invisible Man, The (1933)",Horror|Sci-Fi,0024184
3840,3933,"Killer Shrews, The (1959)",Horror|Sci-Fi,0052969
3841,3934,Kronos (1957),Sci-Fi,0050610
3842,3936,"Phantom of the Opera, The (1943)",Drama|Thriller,0036261
3843,3937,Runaway (1984),Sci-Fi|Thriller,0088024
3844,3938,"Slumber Party Massacre, The (1982)",Horror,0084695
3845,3939,"Slumber Party Massacre II, The (1987)",Horror,0093996
3846,3940,"Slumber Party Massacre III, The (1990)",Horror,0100639
3847,3941,Sorority House Massacre (1986),Horror,0091990
3848,3942,Sorority House Massacre II (1990),Horror,0100663
3849,3943,Bamboozled (2000),Comedy,0215545
3850,3944,Bootmen (2000),Comedy|Drama,0210584
3851,3945,Digimon: The Movie (2000),Adventure|Animation|Children's,0259974
3852,3946,Get Carter (2000),Action|Drama|Thriller,0208988
3853,3947,Get Carter (1971),Thriller,0067128
3854,3948,Meet the Parents (2000),Comedy,0212338
3855,3949,Requiem for a Dream (2000),Drama,0180093
3856,3950,Tigerland (2000),Drama,0170691
3857,3951,Two Family House (2000),Drama,0202641
3858,3952,"Contender, The (2000)",Drama|Thriller,0208874

In [19]:
#Should have 7 characters in the imdbId field in MovieTweetings Dataset

movies_MT['imdbId'] = movies_MT['imdbId'].apply(lambda x: '{0:0>7}'.format(x))

In [20]:
movies_MT

,imdbId,title,genre
0,0000008,Edison Kinetoscopic Record of a Sneeze (1894),Documentary|Short
1,0000010,La sortie des usines Lumière (1895),Documentary|Short
2,0000012,The Arrival of a Train (1896),Documentary|Short
3,0000025,The Oxford and Cambridge University Boat Race ...,NaN
4,0000091,Le manoir du diable (1896),Short|Horror
5,0000417,Le voyage dans la lune (1902),Short|Adventure|Fantasy
6,0000439,The Great Train Robbery (1903),Short|Action|Crime
7,0000443,"Hiawatha, the Messiah of the Ojibway (1903)",NaN
8,0000628,The Adventures of Dollie (1908),Action|Short
9,0000833,The Country Doctor (1909),Short|Drama
10,0001223,Frankenstein (1910),Short|Fantasy|Horror
11,0001740,The Lonedale Operator (1911),Short|Drama|Romance
12,0002101,Cleopatra (1912),Drama|History
13,0002130,L'inferno (1911),Adventure|Drama|Fantasy
14,0002354,Max et Jane veulent faire du théâtre (1911),Short|Comedy
15,0002844,Fantômas - À l'ombre de la guillotine (1913),Crime|Drama
16,0003740,Cabiria (1914),Adventure|Drama|History
17,0003863,Dough and Dynamite (1914),Comedy|Short
18,0004099,"His Majesty, the Scarecrow of Oz (1914)",Family|Fantasy|Adventure
19,0004100,His Musical Career (1914),Short|Comedy
20,0004101,His New Profession (1914),Short|Comedy
21,0004210,Laughing Gas (1914),Short|Comedy
22,0004395,The New Janitor (1914),Short|Comedy
23,0004457,The Patchwork Girl of Oz (1914),Adventure|Family|Fantasy
24,0004518,Recreation (1914),Comedy|Short
25,0004546,The Rounders (1914),Comedy|Short
26,0004936,The Bank (1915),Comedy|Short
27,0004972,The Birth of a Nation (1915),Drama|History|War
28,0005074,The Champion (1915),Short|Comedy|Sport
29,0005078,The Cheat (1915),Drama
...,...,...,...
30562,7746238,Chrisye (2017),NaN
30563,7752054,Katt Williams: Great America (2018),NaN
30564,7752142,Todd Glass: Act Happy (2018),NaN
30565,7761204,WWE Royal Rumble (2018),NaN
30566,7763020,Dovlatov (2018),NaN
30567,7768848,Wild Wild Country (2018),NaN
30568,7807486,UFC 220: Miocic vs. Ngannou (2018),NaN
30569,7830574,Ricky Gervais: Humanity (2018),NaN
30570,7833952,Talq Senaee (2018),NaN
30571,7843946,Dilan 1990 (2018),NaN
30572,7853242,Love Per Square Foot (2018),NaN
30573,7865404,Yo! My Saint (2018),NaN
30574,7871636,Deliha 2 (2018),NaN
30575,7882406,Dört Köse (2017),NaN
30576,7888178,Jar of Ashes (2018),NaN
30577,7917456,Slightly Off (2018),NaN
30578,7923374,Badang (2018),NaN
30579,7923890,Justin Timberlake: Say Something (2018),NaN
30580,7924798,Fred Armisen: Standup For Drummers (2018),NaN
30581,7924808,Derren Brown: The Push (2018),NaN
30582,7924820,The Trader (2018),NaN
30583,7942708,KL Special Force (2018),NaN
30584,7959216,Utøya 22. juli (2018),NaN
30585,7967954,Lee Chong Wei (2018),NaN
30586,7983844,Take Your Pills (2018),NaN
30587,8005338,Chris Rock: Tamborine (2018),NaN
30588,8043254,Sirb al-Hamam (2018),NaN
30589,8080268,Rock 'n' Roll Guns for Hire: The Story of the ...,NaN
30590,8080556,The Director and The Jedi (2018),NaN
30591,8088944,Ban-deu-si Jab-neun-da (2017),NaN

In [23]:
movielens_1M_final_dataset = pd.merge (movielens_1M_final, movies_MT, on='imdbId')

In [164]:
#MovieLens final dataset with correct ImdbID = 2859 movies

movielens_1M_final_dataset

,movieid,title_x,genre_x,imdbId,title_y,genre_y
0,1,Toy Story (1995),Animation|Children's|Comedy,0114709,Toy Story (1995),Animation|Adventure|Comedy
1,2,Jumanji (1995),Adventure|Children's|Fantasy,0113497,Jumanji (1995),Adventure|Family|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance,0113228,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama,0114885,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy,0113041,Father of the Bride Part II (1995),Comedy
5,6,Heat (1995),Action|Crime|Thriller,0113277,Heat (1995),Action|Crime|Drama
6,7,Sabrina (1995),Comedy|Romance,0114319,Sabrina (1995),Comedy|Drama
7,9,Sudden Death (1995),Action,0114576,Sudden Death (1995),Action|Crime|Thriller
8,10,GoldenEye (1995),Action|Adventure|Thriller,0113189,GoldenEye (1995),Action|Adventure|Sci-Fi
9,11,"American President, The (1995)",Comedy|Drama|Romance,0112346,The American President (1995),Comedy|Drama|Romance
10,12,Dracula: Dead and Loving It (1995),Comedy|Horror,0112896,Dracula: Dead and Loving It (1995),Comedy|Fantasy|Horror
11,13,Balto (1995),Animation|Children's,0112453,Balto (1995),Animation|Adventure|Drama
12,14,Nixon (1995),Drama,0113987,Nixon (1995),Biography|Drama|History
13,15,Cutthroat Island (1995),Action|Adventure|Romance,0112760,Cutthroat Island (1995),Action|Adventure|Comedy
14,16,Casino (1995),Drama|Thriller,0112641,Casino (1995),Biography|Crime|Drama
15,17,Sense and Sensibility (1995),Drama|Romance,0114388,Sense and Sensibility (1995),Drama|Romance
16,18,Four Rooms (1995),Thriller,0113101,Four Rooms (1995),Comedy|Crime
17,19,Ace Ventura: When Nature Calls (1995),Comedy,0112281,Ace Ventura: When Nature Calls (1995),Adventure|Comedy
18,20,Money Train (1995),Action,0113845,Money Train (1995),Action|Comedy|Crime
19,21,Get Shorty (1995),Action|Comedy|Drama,0113161,Get Shorty (1995),Comedy|Crime|Thriller
20,22,Copycat (1995),Crime|Drama|Thriller,0112722,Copycat (1995),Crime|Drama|Mystery
21,23,Assassins (1995),Thriller,0112401,Assassins (1995),Action|Crime|Thriller
22,24,Powder (1995),Drama|Sci-Fi,0114168,Powder (1995),Drama|Fantasy|Mystery
23,25,Leaving Las Vegas (1995),Drama|Romance,0113627,Leaving Las Vegas (1995),Drama|Romance
24,26,Othello (1995),Drama,0114057,Othello (1995),Drama|Romance
25,27,Now and Then (1995),Drama,0114011,Now and Then (1995),Comedy|Drama
26,28,Persuasion (1995),Romance,0114117,Persuasion (1995),Drama|Romance
27,29,"City of Lost Children, The (1995)",Adventure|Sci-Fi,0112682,La cité des enfants perdus (1995),Fantasy|Sci-Fi
28,30,Shanghai Triad (Yao a yao yao dao waipo qiao) ...,Drama,0115012,"Yao a yao, yao dao wai po qiao (1995)",Crime|Drama
29,31,Dangerous Minds (1995),Drama,0112792,Dangerous Minds (1995),Biography|Drama
...,...,...,...,...,...,...
2829,3914,"Broken Hearts Club, The (2000)",Drama,0222850,The Broken Hearts Club: A Romantic Comedy (2000),Comedy|Drama|Romance
2830,3915,Girlfight (2000),Drama,0210075,Girlfight (2000),Drama|Sport
2831,3916,Remember the Titans (2000),Drama,0210945,Remember the Titans (2000),Biography|Drama|Sport
2832,3917,Hellraiser (1987),Horror,0093177,Hellraiser (1987),Horror
2833,3918,Hellbound: Hellraiser II (1988),Horror,0095294,Hellbound: Hellraiser II (1988),Horror|Thriller
2834,3919,Hellraiser III: Hell on Earth (1992),Horror,0104409,Hellraiser III: Hell on Earth (1992),Horror
2835,3920,"Faraway, So Close (In Weiter Ferne, So Nah!) (...",Drama|Fantasy,0107209,"In weiter Ferne, so nah! (1993)",Fantasy|Drama|Mystery
2836,3923,Return of the Fly (1959),Horror|Sci-Fi,0053219,Return of the Fly (1959),Drama|Fantasy|Horror
2837,3925,Stranger Than Paradise (1984),Comedy,0088184,Stranger Than Paradise (1984),Comedy|Drama
2838,3926,Voyage to the Bottom of the Sea (1961),Adventure|Sci-Fi,0055608,Voyage to the Bottom of the Sea (1961),Action|Adventure|Sci-Fi
2839,3927,Fantastic Voyage (1966),Adventure|Sci-Fi,0060397,Fantastic Voyage (1966),Adventure|Family|Sci-Fi
2840,3928,Abbott and Costello Meet Frankenstein (1948),Comedy|Horror,0040068,Bud Abbott Lou Costello Meet Frankenstein (1948),Comedy|Horror|Sci-Fi
2841,3929,"Bank Dick, The (1940)",Comedy,0032234,The Bank Dick (1940),Comedy
2842,3930,"Creature From the Black Lagoon, The (1954)",Horror,0046876,Creature from the Black Lagoon (1954),Adventure|Horror|Sci-Fi
2843,3932,"Invisible Man, The (1933)",Horror|Sci-Fi,0024184,The Invisible Man (1933),Horror|Sci-Fi
2844,3933,"Killer Shrews, The (1959)",Horror|Sci-Fi,0052969,The Killer Shrews (1959),Horror|Sci-Fi
2845,3936,"Phantom of the Opera, The (1943)",Drama|Thriller,0036261,Phantom of the Opera (1943),Drama|Horror|Music
2846,3937,Runaway (1984),Sci-Fi|Thriller,0088024,Runaway (1984),Action|Crime|Sci-Fi
2847,3938,"Slumber Party Massacre, The (1982)",Horror,0084695,The Slumber Party Massacre (1982),Comedy|Horror
2848,3939,"Slumber Party Massacre II, The (1987)",Horror,0093996,Slumber Party Massacre II (1987),Comedy|Horror
2849,3941,Sorority House Massacre (1986),Horror,0091990,Sorority House Massacre (1986),Horror
2850,3942,Sorority House Massacre II (1990),Horror,0100663,Sorority House Massacre II (1990),Comedy|Horror|Thriller
2851,3943,Bamboozled (2000),Comedy,0215545,Bamboozled (2000),Comedy|Drama|Music
2852,3946,Get Carter (2000),Action|Drama|Thriller,0208988,Get Carter (2000),Action|Crime|Drama
2853,3947,Get Carter (1971),Thriller,0067128,Get Carter (1971),Crime|Thriller
2854,3948,Meet the Parents (2000),Comedy,0212338,Meet the Parents (2000),Comedy
2855,3949,Requiem for a Dream (2000),Drama,0180093,Requiem for a Dream (2000),Drama
2856,3950,Tigerland (2000),Drama,0170691,Tigerland (2000),Drama|War
2857,3951,Two Family House (2000),Drama,0202641,Two Family House (2000),Comedy|Drama|Romance
2858,3952,"Contender, The (2000)",Drama|Thriller,0208874,The Contender (2000),Drama|Thriller

In [163]:
movielens_1M_final_dataset.to_csv('/home/ishu/Master_Thesis/Data_Comparison/updated_movielens_files/movielens_1M_final_dataset.csv')

In [29]:
#Load the rating dataset from Movielens 1M

ratings = pd.read_table('ratings.dat',sep='::',names=['user','movieid','rating','time'], engine='python')

In [31]:
del ratings['time']

In [32]:
ratings.head()

   user  movieid  rating
0     1     1193       5
1     1      661       3
2     1      914       3
3     1     3408       4
4     1     2355       5

In [33]:
ratings

         user  movieid  rating
0           1     1193       5
1           1      661       3
2           1      914       3
3           1     3408       4
4           1     2355       5
5           1     1197       3
6           1     1287       5
7           1     2804       5
8           1      594       4
9           1      919       4
10          1      595       5
11          1      938       4
12          1     2398       4
13          1     2918       4
14          1     1035       5
15          1     2791       4
16          1     2687       3
17          1     2018       4
18          1     3105       5
19          1     2797       4
20          1     2321       3
21          1      720       3
22          1     1270       5
23          1      527       5
24          1     2340       3
25          1       48       5
26          1     1097       4
27          1     1721       4
28          1     1545       4
29          1      745       3
...       ...      ...     ...
1000179  6040     2762       4
1000180  6040     1036       3
1000181  6040      508       4
1000182  6040     1041       4
1000183  6040     3735       4
1000184  6040     2791       4
1000185  6040     2794       1
1000186  6040      527       5
1000187  6040     2003       1
1000188  6040      535       4
1000189  6040     2010       5
1000190  6040     2011       4
1000191  6040     3751       4
1000192  6040     2019       5
1000193  6040      541       4
1000194  6040     1077       5
1000195  6040     1079       2
1000196  6040      549       4
1000197  6040     2020       3
1000198  6040     2021       3
1000199  6040     2022       5
1000200  6040     2028       5
1000201  6040     1080       4
1000202  6040     1089       4
1000203  6040     1090       3
1000204  6040     1091       1
1000205  6040     1094       5
1000206  6040      562       5
1000207  6040     1096       4
1000208  6040     1097       4

[1000209 rows x 3 columns]

In [54]:
ratings['movieid'].nunique()

3706

In [47]:
#The ratings are segregated.

ratings_1M = ratings.loc[ratings['movieid'].isin(movielens_1M_final_dataset['movieid'])].copy()

In [55]:
ratings_1M

         user  movieid  rating
0           1     1193       5
1           1      661       3
2           1      914       3
3           1     3408       4
4           1     2355       5
5           1     1197       3
6           1     1287       5
7           1     2804       5
8           1      594       4
9           1      919       4
10          1      595       5
11          1      938       4
12          1     2398       4
13          1     2918       4
14          1     1035       5
15          1     2791       4
16          1     2687       3
17          1     2018       4
18          1     3105       5
19          1     2797       4
20          1     2321       3
22          1     1270       5
23          1      527       5
24          1     2340       3
25          1       48       5
26          1     1097       4
27          1     1721       4
28          1     1545       4
29          1      745       3
30          1     2294       4
...       ...      ...     ...
1000179  6040     2762       4
1000180  6040     1036       3
1000181  6040      508       4
1000182  6040     1041       4
1000183  6040     3735       4
1000184  6040     2791       4
1000185  6040     2794       1
1000186  6040      527       5
1000187  6040     2003       1
1000188  6040      535       4
1000189  6040     2010       5
1000190  6040     2011       4
1000191  6040     3751       4
1000192  6040     2019       5
1000193  6040      541       4
1000194  6040     1077       5
1000195  6040     1079       2
1000196  6040      549       4
1000197  6040     2020       3
1000198  6040     2021       3
1000199  6040     2022       5
1000200  6040     2028       5
1000201  6040     1080       4
1000202  6040     1089       4
1000203  6040     1090       3
1000204  6040     1091       1
1000205  6040     1094       5
1000206  6040      562       5
1000207  6040     1096       4
1000208  6040     1097       4

[967412 rows x 3 columns]

In [50]:
ratings_1M.to_csv('ratings_1M.csv')

In [52]:
ratings_1M['movieid'].nunique()

2835

In [56]:
#Calculate the frequency of the movies - how many times the movies have been rated/occured

moviesid_frequency = pd.crosstab(index = ratings_1M["movieid"], columns="frequency")

In [60]:
moviesid_frequency = moviesid_frequency.sort_values('frequency', ascending = False).head(40)

In [61]:
moviesid_frequency

col_0    frequency
movieid
2858          3428
260           2991
1196          2990
1210          2883
480           2672
2028          2653
589           2649
2571          2590
1270          2583
593           2578
1580          2538
1198          2514
608           2513
2762          2459
110           2443
2396          2369
1197          2318
527           2304
1617          2288
1265          2278
1097          2269
2628          2250
2997          2241
318           2227
858           2223
356           2194
2716          2181
296           2171
1240          2098
1             2077
1214          2024
2916          1996
457           1995
3578          1924
1200          1820
541           1800
2987          1799
1259          1785
50            1783
34            1751

In [62]:
moviesid_frequency.to_csv('/home/ishu/Master_Thesis/Data_Comparison/moviesid_frequency.csv')

In [63]:
movie_popular40 = pd.read_csv('/home/ishu/Master_Thesis/Data_Comparison/temp_files/moviesid_frequency.csv')

In [64]:
movie_popular40

    movieid  frequency
0      2858       3428
1       260       2991
2      1196       2990
3      1210       2883
4       480       2672
5      2028       2653
6       589       2649
7      2571       2590
8      1270       2583
9       593       2578
10     1580       2538
11     1198       2514
12      608       2513
13     2762       2459
14      110       2443
15     2396       2369
16     1197       2318
17      527       2304
18     1617       2288
19     1265       2278
20     1097       2269
21     2628       2250
22     2997       2241
23      318       2227
24      858       2223
25      356       2194
26     2716       2181
27      296       2171
28     1240       2098
29        1       2077
30     1214       2024
31     2916       1996
32      457       1995
33     3578       1924
34     1200       1820
35      541       1800
36     2987       1799
37     1259       1785
38       50       1783
39       34       1751

In [65]:
initial_seed_popularity = pd.merge(movie_popular40,movielens_1M_final_dataset, on='movieid')

In [66]:
#Top 40 movies based on popularity

initial_seed_popularity

,movieid,frequency,title_x,genre_x,imdbId,title_y,genre_y
0,2858,3428,American Beauty (1999),Comedy|Drama,0169547,American Beauty (1999),Drama|Romance
1,260,2991,Star Wars: Episode IV - A New Hope (1977),Action|Adventure|Fantasy|Sci-Fi,0076759,Star Wars: Episode IV - A New Hope (1977),Action|Adventure|Fantasy
2,1196,2990,Star Wars: Episode V - The Empire Strikes Back...,Action|Adventure|Drama|Sci-Fi|War,0080684,Star Wars: Episode V - The Empire Strikes Back...,Action|Adventure|Fantasy
3,1210,2883,Star Wars: Episode VI - Return of the Jedi (1983),Action|Adventure|Romance|Sci-Fi|War,0086190,Star Wars: Episode VI - Return of the Jedi (1983),Action|Adventure|Fantasy
4,480,2672,Jurassic Park (1993),Action|Adventure|Sci-Fi,0107290,Jurassic Park (1993),Adventure|Sci-Fi|Thriller
5,2028,2653,Saving Private Ryan (1998),Action|Drama|War,0120815,Saving Private Ryan (1998),Action|Drama|War
6,589,2649,Terminator 2: Judgment Day (1991),Action|Sci-Fi|Thriller,0103064,Terminator 2: Judgment Day (1991),Action|Sci-Fi
7,2571,2590,"Matrix, The (1999)",Action|Sci-Fi|Thriller,0133093,The Matrix (1999),Action|Sci-Fi
8,1270,2583,Back to the Future (1985),Comedy|Sci-Fi,0088763,Back to the Future (1985),Adventure|Comedy|Sci-Fi
9,593,2578,"Silence of the Lambs, The (1991)",Drama|Thriller,0102926,The Silence of the Lambs (1991),Crime|Drama|Thriller
10,1580,2538,Men in Black (1997),Action|Adventure|Comedy|Sci-Fi,0119654,Men in Black (1997),Comedy|Sci-Fi
11,1198,2514,Raiders of the Lost Ark (1981),Action|Adventure,0082971,Raiders of the Lost Ark (1981),Action|Adventure
12,608,2513,Fargo (1996),Crime|Drama|Thriller,0116282,Fargo (1996),Crime|Drama|Thriller
13,2762,2459,"Sixth Sense, The (1999)",Thriller,0167404,The Sixth Sense (1999),Drama|Mystery|Thriller
14,110,2443,Braveheart (1995),Action|Drama|War,0112573,Braveheart (1995),Biography|Drama|History
15,2396,2369,Shakespeare in Love (1998),Comedy|Romance,0138097,Shakespeare in Love (1998),Comedy|Drama|Romance
16,1197,2318,"Princess Bride, The (1987)",Action|Adventure|Comedy|Romance,0093779,The Princess Bride (1987),Adventure|Comedy|Family
17,527,2304,Schindler's List (1993),Drama|War,0108052,Schindler's List (1993),Biography|Drama|History
18,1617,2288,L.A. Confidential (1997),Crime|Film-Noir|Mystery|Thriller,0119488,L.A. Confidential (1997),Crime|Drama|Mystery
19,1265,2278,Groundhog Day (1993),Comedy|Romance,0107048,Groundhog Day (1993),Comedy|Fantasy|Romance
20,1097,2269,E.T. the Extra-Terrestrial (1982),Children's|Drama|Fantasy|Sci-Fi,0083866,E.T. the Extra-Terrestrial (1982),Family|Sci-Fi
21,2628,2250,Star Wars: Episode I - The Phantom Menace (1999),Action|Adventure|Fantasy|Sci-Fi,0120915,Star Wars: Episode I - The Phantom Menace (1999),Action|Adventure|Fantasy
22,2997,2241,Being John Malkovich (1999),Comedy,0120601,Being John Malkovich (1999),Comedy|Drama|Fantasy
23,318,2227,"Shawshank Redemption, The (1994)",Drama,0111161,The Shawshank Redemption (1994),Crime|Drama
24,858,2223,"Godfather, The (1972)",Action|Crime|Drama,0068646,The Godfather (1972),Crime|Drama
25,356,2194,Forrest Gump (1994),Comedy|Romance|War,0109830,Forrest Gump (1994),Drama|Romance
26,2716,2181,Ghostbusters (1984),Comedy|Horror,0087332,Ghost Busters (1984),Adventure|Comedy|Fantasy
27,296,2171,Pulp Fiction (1994),Crime|Drama,0110912,Pulp Fiction (1994),Crime|Drama
28,1240,2098,"Terminator, The (1984)",Action|Sci-Fi|Thriller,0088247,The Terminator (1984),Action|Sci-Fi
29,1,2077,Toy Story (1995),Animation|Children's|Comedy,0114709,Toy Story (1995),Animation|Adventure|Comedy
30,1214,2024,Alien (1979),Action|Horror|Sci-Fi|Thriller,0078748,Alien (1979),Horror|Sci-Fi
31,2916,1996,Total Recall (1990),Action|Adventure|Sci-Fi|Thriller,0100802,Total Recall (1990),Action|Sci-Fi
32,457,1995,"Fugitive, The (1993)",Action|Thriller,0106977,The Fugitive (1993),Action|Adventure|Crime
33,3578,1924,Gladiator (2000),Action|Drama,0172495,Gladiator (2000),Action|Drama
34,1200,1820,Aliens (1986),Action|Sci-Fi|Thriller|War,0090605,Aliens (1986),Action|Horror|Sci-Fi
35,541,1800,Blade Runner (1982),Film-Noir|Sci-Fi,0083658,Blade Runner (1982),Sci-Fi|Thriller
36,2987,1799,Who Framed Roger Rabbit? (1988),Adventure|Animation|Film-Noir,0096438,Who Framed Roger Rabbit (1988),Animation|Comedy|Crime
37,1259,1785,Stand by Me (1986),Adventure|Comedy|Drama,0092005,Stand by Me (1986),Adventure|Drama
38,50,1783,"Usual Suspects, The (1995)",Crime|Thriller,0114814,The Usual Suspects (1995),Crime|Drama|Mystery
39,34,1751,Babe (1995),Children's|Comedy|Drama,0112431,Babe (1995),Comedy|Drama|Family

In [68]:
initial_seed_popularity.to_csv('/home/ishu/Master_Thesis/Data_Comparison/initial_seed_files/initial_seed_popularity.csv')

In [70]:
import numpy
numpy.log10(40)

1.6020599913279625

In [86]:
moviesid_frequency = pd.crosstab(index = ratings_1M["movieid"], columns="frequency")

In [91]:
moviesid_frequency

col_0    frequency  log_value
movieid
2858          3428   3.535041
260           2991   3.475816
1196          2990   3.475671
1210          2883   3.459845
480           2672   3.426836
2028          2653   3.423737
589           2649   3.423082
2571          2590   3.413300
1270          2583   3.412124
593           2578   3.411283
1580          2538   3.404492
1198          2514   3.400365
608           2513   3.400192
2762          2459   3.390759
110           2443   3.387923
2396          2369   3.374565
1197          2318   3.365113
527           2304   3.362482
1617          2288   3.359456
1265          2278   3.357554
1097          2269   3.355834
2628          2250   3.352183
2997          2241   3.350442
318           2227   3.347720
858           2223   3.346939
356           2194   3.341237
2716          2181   3.338656
296           2171   3.336660
1240          2098   3.321805
1             2077   3.317436
...            ...        ...
3651             2   0.301030
3294             2   0.301030
2845             1   0.000000
3315             1   0.000000
2308             1   0.000000
127              1   0.000000
3229             1   0.000000
2214             1   0.000000
3209             1   0.000000
1908             1   0.000000
3280             1   0.000000
2584             1   0.000000
1118             1   0.000000
2438             1   0.000000
2235             1   0.000000
2226             1   0.000000
868              1   0.000000
701              1   0.000000
2742             1   0.000000
3656             1   0.000000
3172             1   0.000000
584              1   0.000000
3647             1   0.000000
3065             1   0.000000
2213             1   0.000000
3890             1   0.000000
1724             1   0.000000
1470             1   0.000000
872              1   0.000000
2563             1   0.000000

[2835 rows x 2 columns]

In [92]:
moviesid_frequency.to_csv('moviesid_frequency_log.csv')

In [88]:
moviesid_frequency = moviesid_frequency.assign (log_value = numpy.log10(moviesid_frequency))

In [93]:
moviesid_frequency_top40 = moviesid_frequency.sort_values('frequency', ascending = False).head(40)

In [96]:
moviesid_frequency_top40.to_csv('/home/ishu/Master_Thesis/Data_Comparison/temp_files/moviesid_frequency_top40.csv')

In [97]:
moviesid_logtop40 = pd.read_csv('/home/ishu/Master_Thesis/Data_Comparison/temp_files/moviesid_frequency_top40.csv')

In [99]:
initial_seed_log_popularity = pd.merge(moviesid_logtop40, movielens_1M_final_dataset, on='movieid')

In [100]:
#Top 40 movies based on log(popularity)

initial_seed_log_popularity

,movieid,frequency,log_value,title_x,genre_x,imdbId,title_y,genre_y
0,2858,3428,3.535041,American Beauty (1999),Comedy|Drama,0169547,American Beauty (1999),Drama|Romance
1,260,2991,3.475816,Star Wars: Episode IV - A New Hope (1977),Action|Adventure|Fantasy|Sci-Fi,0076759,Star Wars: Episode IV - A New Hope (1977),Action|Adventure|Fantasy
2,1196,2990,3.475671,Star Wars: Episode V - The Empire Strikes Back...,Action|Adventure|Drama|Sci-Fi|War,0080684,Star Wars: Episode V - The Empire Strikes Back...,Action|Adventure|Fantasy
3,1210,2883,3.459845,Star Wars: Episode VI - Return of the Jedi (1983),Action|Adventure|Romance|Sci-Fi|War,0086190,Star Wars: Episode VI - Return of the Jedi (1983),Action|Adventure|Fantasy
4,480,2672,3.426836,Jurassic Park (1993),Action|Adventure|Sci-Fi,0107290,Jurassic Park (1993),Adventure|Sci-Fi|Thriller
5,2028,2653,3.423737,Saving Private Ryan (1998),Action|Drama|War,0120815,Saving Private Ryan (1998),Action|Drama|War
6,589,2649,3.423082,Terminator 2: Judgment Day (1991),Action|Sci-Fi|Thriller,0103064,Terminator 2: Judgment Day (1991),Action|Sci-Fi
7,2571,2590,3.413300,"Matrix, The (1999)",Action|Sci-Fi|Thriller,0133093,The Matrix (1999),Action|Sci-Fi
8,1270,2583,3.412124,Back to the Future (1985),Comedy|Sci-Fi,0088763,Back to the Future (1985),Adventure|Comedy|Sci-Fi
9,593,2578,3.411283,"Silence of the Lambs, The (1991)",Drama|Thriller,0102926,The Silence of the Lambs (1991),Crime|Drama|Thriller
10,1580,2538,3.404492,Men in Black (1997),Action|Adventure|Comedy|Sci-Fi,0119654,Men in Black (1997),Comedy|Sci-Fi
11,1198,2514,3.400365,Raiders of the Lost Ark (1981),Action|Adventure,0082971,Raiders of the Lost Ark (1981),Action|Adventure
12,608,2513,3.400192,Fargo (1996),Crime|Drama|Thriller,0116282,Fargo (1996),Crime|Drama|Thriller
13,2762,2459,3.390759,"Sixth Sense, The (1999)",Thriller,0167404,The Sixth Sense (1999),Drama|Mystery|Thriller
14,110,2443,3.387923,Braveheart (1995),Action|Drama|War,0112573,Braveheart (1995),Biography|Drama|History
15,2396,2369,3.374565,Shakespeare in Love (1998),Comedy|Romance,0138097,Shakespeare in Love (1998),Comedy|Drama|Romance
16,1197,2318,3.365113,"Princess Bride, The (1987)",Action|Adventure|Comedy|Romance,0093779,The Princess Bride (1987),Adventure|Comedy|Family
17,527,2304,3.362482,Schindler's List (1993),Drama|War,0108052,Schindler's List (1993),Biography|Drama|History
18,1617,2288,3.359456,L.A. Confidential (1997),Crime|Film-Noir|Mystery|Thriller,0119488,L.A. Confidential (1997),Crime|Drama|Mystery
19,1265,2278,3.357554,Groundhog Day (1993),Comedy|Romance,0107048,Groundhog Day (1993),Comedy|Fantasy|Romance
20,1097,2269,3.355834,E.T. the Extra-Terrestrial (1982),Children's|Drama|Fantasy|Sci-Fi,0083866,E.T. the Extra-Terrestrial (1982),Family|Sci-Fi
21,2628,2250,3.352183,Star Wars: Episode I - The Phantom Menace (1999),Action|Adventure|Fantasy|Sci-Fi,0120915,Star Wars: Episode I - The Phantom Menace (1999),Action|Adventure|Fantasy
22,2997,2241,3.350442,Being John Malkovich (1999),Comedy,0120601,Being John Malkovich (1999),Comedy|Drama|Fantasy
23,318,2227,3.347720,"Shawshank Redemption, The (1994)",Drama,0111161,The Shawshank Redemption (1994),Crime|Drama
24,858,2223,3.346939,"Godfather, The (1972)",Action|Crime|Drama,0068646,The Godfather (1972),Crime|Drama
25,356,2194,3.341237,Forrest Gump (1994),Comedy|Romance|War,0109830,Forrest Gump (1994),Drama|Romance
26,2716,2181,3.338656,Ghostbusters (1984),Comedy|Horror,0087332,Ghost Busters (1984),Adventure|Comedy|Fantasy
27,296,2171,3.336660,Pulp Fiction (1994),Crime|Drama,0110912,Pulp Fiction (1994),Crime|Drama
28,1240,2098,3.321805,"Terminator, The (1984)",Action|Sci-Fi|Thriller,0088247,The Terminator (1984),Action|Sci-Fi
29,1,2077,3.317436,Toy Story (1995),Animation|Children's|Comedy,0114709,Toy Story (1995),Animation|Adventure|Comedy
30,1214,2024,3.306211,Alien (1979),Action|Horror|Sci-Fi|Thriller,0078748,Alien (1979),Horror|Sci-Fi
31,2916,1996,3.300161,Total Recall (1990),Action|Adventure|Sci-Fi|Thriller,0100802,Total Recall (1990),Action|Sci-Fi
32,457,1995,3.299943,"Fugitive, The (1993)",Action|Thriller,0106977,The Fugitive (1993),Action|Adventure|Crime
33,3578,1924,3.284205,Gladiator (2000),Action|Drama,0172495,Gladiator (2000),Action|Drama
34,1200,1820,3.260071,Aliens (1986),Action|Sci-Fi|Thriller|War,0090605,Aliens (1986),Action|Horror|Sci-Fi
35,541,1800,3.255273,Blade Runner (1982),Film-Noir|Sci-Fi,0083658,Blade Runner (1982),Sci-Fi|Thriller
36,2987,1799,3.255031,Who Framed Roger Rabbit? (1988),Adventure|Animation|Film-Noir,0096438,Who Framed Roger Rabbit (1988),Animation|Comedy|Crime
37,1259,1785,3.251638,Stand by Me (1986),Adventure|Comedy|Drama,0092005,Stand by Me (1986),Adventure|Drama
38,50,1783,3.251151,"Usual Suspects, The (1995)",Crime|Thriller,0114814,The Usual Suspects (1995),Crime|Drama|Mystery
39,34,1751,3.243286,Babe (1995),Children's|Comedy|Drama,0112431,Babe (1995),Comedy|Drama|Family

In [101]:
initial_seed_log_popularity.to_csv('/home/ishu/Master_Thesis/Data_Comparison/initial_seed_files/initial_seed_log_popularity.csv')

In [103]:
ratings_1M

         user  movieid  rating
0           1     1193       5
1           1      661       3
2           1      914       3
3           1     3408       4
4           1     2355       5
5           1     1197       3
6           1     1287       5
7           1     2804       5
8           1      594       4
9           1      919       4
10          1      595       5
11          1      938       4
12          1     2398       4
13          1     2918       4
14          1     1035       5
15          1     2791       4
16          1     2687       3
17          1     2018       4
18          1     3105       5
19          1     2797       4
20          1     2321       3
22          1     1270       5
23          1      527       5
24          1     2340       3
25          1       48       5
26          1     1097       4
27          1     1721       4
28          1     1545       4
29          1      745       3
30          1     2294       4
...       ...      ...     ...
1000179  6040     2762       4
1000180  6040     1036       3
1000181  6040      508       4
1000182  6040     1041       4
1000183  6040     3735       4
1000184  6040     2791       4
1000185  6040     2794       1
1000186  6040      527       5
1000187  6040     2003       1
1000188  6040      535       4
1000189  6040     2010       5
1000190  6040     2011       4
1000191  6040     3751       4
1000192  6040     2019       5
1000193  6040      541       4
1000194  6040     1077       5
1000195  6040     1079       2
1000196  6040      549       4
1000197  6040     2020       3
1000198  6040     2021       3
1000199  6040     2022       5
1000200  6040     2028       5
1000201  6040     1080       4
1000202  6040     1089       4
1000203  6040     1090       3
1000204  6040     1091       1
1000205  6040     1094       5
1000206  6040      562       5
1000207  6040     1096       4
1000208  6040     1097       4

[967412 rows x 3 columns]

In [104]:
#To calculate the variance

ratings_1M_temp = ratings_1M.drop('user', 1)

In [105]:
ratings_1M_temp

         movieid  rating
0           1193       5
1            661       3
2            914       3
3           3408       4
4           2355       5
5           1197       3
6           1287       5
7           2804       5
8            594       4
9            919       4
10           595       5
11           938       4
12          2398       4
13          2918       4
14          1035       5
15          2791       4
16          2687       3
17          2018       4
18          3105       5
19          2797       4
20          2321       3
22          1270       5
23           527       5
24          2340       3
25            48       5
26          1097       4
27          1721       4
28          1545       4
29           745       3
30          2294       4
...          ...     ...
1000179     2762       4
1000180     1036       3
1000181      508       4
1000182     1041       4
1000183     3735       4
1000184     2791       4
1000185     2794       1
1000186      527       5
1000187     2003       1
1000188      535       4
1000189     2010       5
1000190     2011       4
1000191     3751       4
1000192     2019       5
1000193      541       4
1000194     1077       5
1000195     1079       2
1000196      549       4
1000197     2020       3
1000198     2021       3
1000199     2022       5
1000200     2028       5
1000201     1080       4
1000202     1089       4
1000203     1090       3
1000204     1091       1
1000205     1094       5
1000206      562       5
1000207     1096       4
1000208     1097       4

[967412 rows x 2 columns]

In [106]:
ratings_1M_temp = ratings_1M_temp.sort_values('movieid', ascending=True)

In [107]:
ratings_1M_temp

        movieid  rating
52000         1       5
419221        1       5
674934        1       5
330353        1       5
311024        1       5
291053        1       5
23421         1       5
185997        1       4
29526         1       4
429593        1       3
60418         1       5
330484        1       5
992212        1       5
908681        1       5
109536        1       4
414372        1       3
76952         1       5
562007        1       5
601932        1       4
464585        1       3
531890        1       5
753193        1       5
762866        1       4
103752        1       5
972681        1       5
874709        1       5
400172        1       4
511743        1       4
155098        1       5
209109        1       4
...         ...     ...
196905     3952       5
201906     3952       4
96544      3952       5
404337     3952       4
113664     3952       3
152771     3952       4
750245     3952       3
164187     3952       5
359177     3952       4
331249     3952       4
510165     3952       4
244353     3952       3
751812     3952       3
262909     3952       4
285093     3952       4
330625     3952       4
227916     3952       4
2898       3952       4
114188     3952       3
173241     3952       4
531909     3952       4
216562     3952       3
583145     3952       4
243644     3952       3
25188      3952       5
330905     3952       4
148624     3952       5
360394     3952       5
133400     3952       3
992932     3952       4

[967412 rows x 2 columns]

In [109]:
variance_1 = ratings_1M_temp.groupby("movieid")['rating'].var(ddof=True)

In [110]:
variance_2 = ratings_1M_temp.groupby("movieid")['rating'].var(ddof=False)

In [120]:
variance_3 = ratings_1M_temp.groupby("movieid")['rating'].var() #Default it is set as True

In [111]:
variance_1

movieid
1       0.726499
2       0.966627
3       1.148566
4       1.026940
5       1.050802
6       0.873455
7       0.960240
9       1.098913
10      0.794296
11      0.747171
12      1.452673
13      1.113997
14      0.762986
15      1.491403
16      0.819161
17      0.818185
18      1.032745
19      1.389447
20      0.816195
21      0.873938
22      0.954655
23      1.003429
24      1.139482
25      1.195760
26      0.898081
27      0.962295
28      0.760906
29      0.993655
30      1.025546
31      0.929889
          ...
3914    1.383230
3915    1.489939
3916    0.982817
3917    1.545164
3918    1.279994
3919    0.993050
3920    1.223543
3923    0.964899
3925    1.019407
3926    0.656580
3927    0.676505
3928    1.155127
3929    0.938310
3930    1.164101
3932    0.829004
3933    1.533333
3936    0.742519
3937    0.727805
3938    1.148148
3939    1.718462
3941    1.569264
3942    1.285714
3943    1.565680
3946    1.164040
3947    1.402020
3948    1.028594
3949    1.019704
3950    1.094340
3951    1.117949
3952    0.874364
Name: rating, Length: 2835, dtype: float64

In [112]:
variance_2

movieid
1       0.726149
2       0.965248
3       1.146163
4       1.020900
5       1.047252
6       0.872526
7       0.958143
9       1.088139
10      0.793402
11      0.746448
12      1.443594
13      1.102745
14      0.757999
15      1.481188
16      0.817960
17      0.817205
18      1.026167
19      1.385875
20      0.811094
21      0.873293
22      0.952129
23      0.995465
24      1.137656
25      1.194540
26      0.889100
27      0.946520
28      0.756656
29      0.991189
30      1.011687
31      0.923294
          ...
3914    1.363469
3915    1.478207
3916    0.980568
3917    1.539626
3918    1.272330
3919    0.981636
3920    1.205005
3923    0.955621
3925    1.011186
3926    0.652932
3927    0.674561
3928    1.149519
3929    0.931927
3930    1.158881
3932    0.825431
3933    1.437500
3936    0.735890
3937    0.722414
3938    1.105624
3939    1.652367
3941    1.497934
3942    1.239796
3943    1.549371
3946    1.152400
3947    1.376529
3948    1.027401
3949    1.016350
3950    1.074074
3951    1.090000
3952    0.872110
Name: rating, Length: 2835, dtype: float64

In [119]:
from statistics import variance
import numpy as np
print(np.var([1,2,3,4],ddof=0))
print(variance([1,2,3,4]))

1.25
1.6666666666666667

In [121]:
variance_3

movieid
1       0.726499
2       0.966627
3       1.148566
4       1.026940
5       1.050802
6       0.873455
7       0.960240
9       1.098913
10      0.794296
11      0.747171
12      1.452673
13      1.113997
14      0.762986
15      1.491403
16      0.819161
17      0.818185
18      1.032745
19      1.389447
20      0.816195
21      0.873938
22      0.954655
23      1.003429
24      1.139482
25      1.195760
26      0.898081
27      0.962295
28      0.760906
29      0.993655
30      1.025546
31      0.929889
          ...
3914    1.383230
3915    1.489939
3916    0.982817
3917    1.545164
3918    1.279994
3919    0.993050
3920    1.223543
3923    0.964899
3925    1.019407
3926    0.656580
3927    0.676505
3928    1.155127
3929    0.938310
3930    1.164101
3932    0.829004
3933    1.533333
3936    0.742519
3937    0.727805
3938    1.148148
3939    1.718462
3941    1.569264
3942    1.285714
3943    1.565680
3946    1.164040
3947    1.402020
3948    1.028594
3949    1.019704
3950    1.094340
3951    1.117949
3952    0.874364
Name: rating, Length: 2835, dtype: float64

In [123]:
variance_1.to_csv('/home/ishu/Master_Thesis/Data_Comparison/temp_files/variance_1.csv')

In [124]:
variance_2.to_csv('/home/ishu/Master_Thesis/Data_Comparison/temp_files/variance_2.csv')

In [125]:
#Checking for na values
#variance_1.isna().any()
variance_2.isna().any()

False

In [126]:
#Checking for na values
variance_1.isna().any()
#variance_2.isna().any()

True

In [127]:
variance1 = pd.read_csv('/home/ishu/Master_Thesis/Data_Comparison/temp_files/variance_1.csv')

In [128]:
variance1

      movieid  variance_1
0           1    0.726499
1           2    0.966627
2           3    1.148566
3           4    1.026940
4           5    1.050802
5           6    0.873455
6           7    0.960240
7           9    1.098913
8          10    0.794296
9          11    0.747171
10         12    1.452673
11         13    1.113997
12         14    0.762986
13         15    1.491403
14         16    0.819161
15         17    0.818185
16         18    1.032745
17         19    1.389447
18         20    0.816195
19         21    0.873938
20         22    0.954655
21         23    1.003429
22         24    1.139482
23         25    1.195760
24         26    0.898081
25         27    0.962295
26         28    0.760906
27         29    0.993655
28         30    1.025546
29         31    0.929889
...       ...         ...
2805     3914    1.383230
2806     3915    1.489939
2807     3916    0.982817
2808     3917    1.545164
2809     3918    1.279994
2810     3919    0.993050
2811     3920    1.223543
2812     3923    0.964899
2813     3925    1.019407
2814     3926    0.656580
2815     3927    0.676505
2816     3928    1.155127
2817     3929    0.938310
2818     3930    1.164101
2819     3932    0.829004
2820     3933    1.533333
2821     3936    0.742519
2822     3937    0.727805
2823     3938    1.148148
2824     3939    1.718462
2825     3941    1.569264
2826     3942    1.285714
2827     3943    1.565680
2828     3946    1.164040
2829     3947    1.402020
2830     3948    1.028594
2831     3949    1.019704
2832     3950    1.094340
2833     3951    1.117949
2834     3952    0.874364

[2835 rows x 2 columns]

In [129]:
variance1.isna().any()

movieid       False
variance_1     True
dtype: bool

In [133]:
variance1['variance_1']=variance1['variance_1'].fillna(0)

In [134]:
variance1.isna().any()

movieid       False
variance_1    False
dtype: bool

In [135]:
variance1

      movieid  variance_1
0           1    0.726499
1           2    0.966627
2           3    1.148566
3           4    1.026940
4           5    1.050802
5           6    0.873455
6           7    0.960240
7           9    1.098913
8          10    0.794296
9          11    0.747171
10         12    1.452673
11         13    1.113997
12         14    0.762986
13         15    1.491403
14         16    0.819161
15         17    0.818185
16         18    1.032745
17         19    1.389447
18         20    0.816195
19         21    0.873938
20         22    0.954655
21         23    1.003429
22         24    1.139482
23         25    1.195760
24         26    0.898081
25         27    0.962295
26         28    0.760906
27         29    0.993655
28         30    1.025546
29         31    0.929889
...       ...         ...
2805     3914    1.383230
2806     3915    1.489939
2807     3916    0.982817
2808     3917    1.545164
2809     3918    1.279994
2810     3919    0.993050
2811     3920    1.223543
2812     3923    0.964899
2813     3925    1.019407
2814     3926    0.656580
2815     3927    0.676505
2816     3928    1.155127
2817     3929    0.938310
2818     3930    1.164101
2819     3932    0.829004
2820     3933    1.533333
2821     3936    0.742519
2822     3937    0.727805
2823     3938    1.148148
2824     3939    1.718462
2825     3941    1.569264
2826     3942    1.285714
2827     3943    1.565680
2828     3946    1.164040
2829     3947    1.402020
2830     3948    1.028594
2831     3949    1.019704
2832     3950    1.094340
2833     3951    1.117949
2834     3952    0.874364

[2835 rows x 2 columns]

In [136]:
variance2 = pd.read_csv('/home/ishu/Master_Thesis/Data_Comparison/temp_files/variance_2.csv')

In [137]:
variance2

      movieid  variance_2
0           1    0.726149
1           2    0.965248
2           3    1.146163
3           4    1.020900
4           5    1.047252
5           6    0.872526
6           7    0.958143
7           9    1.088139
8          10    0.793402
9          11    0.746448
10         12    1.443594
11         13    1.102745
12         14    0.757999
13         15    1.481188
14         16    0.817960
15         17    0.817205
16         18    1.026167
17         19    1.385875
18         20    0.811094
19         21    0.873293
20         22    0.952129
21         23    0.995465
22         24    1.137656
23         25    1.194540
24         26    0.889100
25         27    0.946520
26         28    0.756656
27         29    0.991189
28         30    1.011687
29         31    0.923294
...       ...         ...
2805     3914    1.363469
2806     3915    1.478207
2807     3916    0.980568
2808     3917    1.539626
2809     3918    1.272330
2810     3919    0.981636
2811     3920    1.205005
2812     3923    0.955621
2813     3925    1.011186
2814     3926    0.652932
2815     3927    0.674561
2816     3928    1.149519
2817     3929    0.931927
2818     3930    1.158881
2819     3932    0.825431
2820     3933    1.437500
2821     3936    0.735890
2822     3937    0.722414
2823     3938    1.105624
2824     3939    1.652367
2825     3941    1.497934
2826     3942    1.239796
2827     3943    1.549371
2828     3946    1.152400
2829     3947    1.376529
2830     3948    1.027401
2831     3949    1.016350
2832     3950    1.074074
2833     3951    1.090000
2834     3952    0.872110

[2835 rows x 2 columns]

In [138]:
variance2.isna().any()

movieid       False
variance_2    False
dtype: bool

In [140]:
variance_values = pd.merge(variance1, variance2, on='movieid')

In [141]:
variance_values

      movieid  variance_1  variance_2
0           1    0.726499    0.726149
1           2    0.966627    0.965248
2           3    1.148566    1.146163
3           4    1.026940    1.020900
4           5    1.050802    1.047252
5           6    0.873455    0.872526
6           7    0.960240    0.958143
7           9    1.098913    1.088139
8          10    0.794296    0.793402
9          11    0.747171    0.746448
10         12    1.452673    1.443594
11         13    1.113997    1.102745
12         14    0.762986    0.757999
13         15    1.491403    1.481188
14         16    0.819161    0.817960
15         17    0.818185    0.817205
16         18    1.032745    1.026167
17         19    1.389447    1.385875
18         20    0.816195    0.811094
19         21    0.873938    0.873293
20         22    0.954655    0.952129
21         23    1.003429    0.995465
22         24    1.139482    1.137656
23         25    1.195760    1.194540
24         26    0.898081    0.889100
25         27    0.962295    0.946520
26         28    0.760906    0.756656
27         29    0.993655    0.991189
28         30    1.025546    1.011687
29         31    0.929889    0.923294
...       ...         ...         ...
2805     3914    1.383230    1.363469
2806     3915    1.489939    1.478207
2807     3916    0.982817    0.980568
2808     3917    1.545164    1.539626
2809     3918    1.279994    1.272330
2810     3919    0.993050    0.981636
2811     3920    1.223543    1.205005
2812     3923    0.964899    0.955621
2813     3925    1.019407    1.011186
2814     3926    0.656580    0.652932
2815     3927    0.676505    0.674561
2816     3928    1.155127    1.149519
2817     3929    0.938310    0.931927
2818     3930    1.164101    1.158881
2819     3932    0.829004    0.825431
2820     3933    1.533333    1.437500
2821     3936    0.742519    0.735890
2822     3937    0.727805    0.722414
2823     3938    1.148148    1.105624
2824     3939    1.718462    1.652367
2825     3941    1.569264    1.497934
2826     3942    1.285714    1.239796
2827     3943    1.565680    1.549371
2828     3946    1.164040    1.152400
2829     3947    1.402020    1.376529
2830     3948    1.028594    1.027401
2831     3949    1.019704    1.016350
2832     3950    1.094340    1.074074
2833     3951    1.117949    1.090000
2834     3952    0.874364    0.872110

[2835 rows x 3 columns]

In [142]:
midfrequency = pd.read_csv('/home/ishu/Master_Thesis/Data_Comparison/temp_files/moviesid_frequency_log.csv')

In [144]:
midfrequency = midfrequency.sort_values('movieid', ascending=True)

In [145]:
midfrequency

      movieid  frequency  log_value
29          1       2077   3.317436
393         2        701   2.845718
648         3        478   2.679428
1541        4        170   2.230449
1062        5        296   2.471292
232         6        940   2.973128
687         7        458   2.660865
1911        9        102   2.008600
258        10        888   2.948413
193        11       1033   3.014100
1602       12        160   2.204120
1938       13         99   1.995635
1627       14        153   2.184691
1660       15        146   2.164353
411        16        682   2.833784
291        17        835   2.921686
1612       18        157   2.195900
815        19        389   2.589950
1601       20        160   2.204120
93         21       1356   3.132260
847        22        378   2.577492
1783       23        126   2.100371
476        24        624   2.795185
218        25        980   2.991226
1933       26        100   2.000000
2225       27         61   1.785330
1501       28        179   2.252853
789        29        403   2.605305
2107       30         74   1.869232
1694       31        141   2.149219
...       ...        ...        ...
2140     3914         70   1.845098
1778     3915        127   2.103804
727      3916        437   2.640481
1110     3917        279   2.445604
1562     3918        167   2.222716
2022     3919         87   1.939519
2168     3920         66   1.819544
1902     3923        104   2.017033
1789     3925        124   2.093422
1488     3926        180   2.255273
931      3927        348   2.541579
1376     3928        206   2.313867
1654     3929        147   2.167317
1295     3930        223   2.348305
1270     3932        232   2.365488
2654     3933         16   1.204120
1855     3936        112   2.049218
1723     3937        135   2.130334
2548     3938         27   1.431364
2555     3939         26   1.414973
2596     3941         22   1.342423
2542     3942         28   1.447158
1956     3943         96   1.982271
1930     3946        100   2.000000
2266     3947         55   1.740363
277      3948        862   2.935507
1035     3949        304   2.482874
2281     3950         54   1.732394
2411     3951         40   1.602060
818      3952        388   2.588832

[2835 rows x 3 columns]

In [146]:
initial_seed = pd.merge (midfrequency,variance_values, on='movieid')

In [147]:
initial_seed

      movieid  frequency  log_value  variance_1  variance_2
0           1       2077   3.317436    0.726499    0.726149
1           2        701   2.845718    0.966627    0.965248
2           3        478   2.679428    1.148566    1.146163
3           4        170   2.230449    1.026940    1.020900
4           5        296   2.471292    1.050802    1.047252
5           6        940   2.973128    0.873455    0.872526
6           7        458   2.660865    0.960240    0.958143
7           9        102   2.008600    1.098913    1.088139
8          10        888   2.948413    0.794296    0.793402
9          11       1033   3.014100    0.747171    0.746448
10         12        160   2.204120    1.452673    1.443594
11         13         99   1.995635    1.113997    1.102745
12         14        153   2.184691    0.762986    0.757999
13         15        146   2.164353    1.491403    1.481188
14         16        682   2.833784    0.819161    0.817960
15         17        835   2.921686    0.818185    0.817205
16         18        157   2.195900    1.032745    1.026167
17         19        389   2.589950    1.389447    1.385875
18         20        160   2.204120    0.816195    0.811094
19         21       1356   3.132260    0.873938    0.873293
20         22        378   2.577492    0.954655    0.952129
21         23        126   2.100371    1.003429    0.995465
22         24        624   2.795185    1.139482    1.137656
23         25        980   2.991226    1.195760    1.194540
24         26        100   2.000000    0.898081    0.889100
25         27         61   1.785330    0.962295    0.946520
26         28        179   2.252853    0.760906    0.756656
27         29        403   2.605305    0.993655    0.991189
28         30         74   1.869232    1.025546    1.011687
29         31        141   2.149219    0.929889    0.923294
...       ...        ...        ...         ...         ...
2805     3914         70   1.845098    1.383230    1.363469
2806     3915        127   2.103804    1.489939    1.478207
2807     3916        437   2.640481    0.982817    0.980568
2808     3917        279   2.445604    1.545164    1.539626
2809     3918        167   2.222716    1.279994    1.272330
2810     3919         87   1.939519    0.993050    0.981636
2811     3920         66   1.819544    1.223543    1.205005
2812     3923        104   2.017033    0.964899    0.955621
2813     3925        124   2.093422    1.019407    1.011186
2814     3926        180   2.255273    0.656580    0.652932
2815     3927        348   2.541579    0.676505    0.674561
2816     3928        206   2.313867    1.155127    1.149519
2817     3929        147   2.167317    0.938310    0.931927
2818     3930        223   2.348305    1.164101    1.158881
2819     3932        232   2.365488    0.829004    0.825431
2820     3933         16   1.204120    1.533333    1.437500
2821     3936        112   2.049218    0.742519    0.735890
2822     3937        135   2.130334    0.727805    0.722414
2823     3938         27   1.431364    1.148148    1.105624
2824     3939         26   1.414973    1.718462    1.652367
2825     3941         22   1.342423    1.569264    1.497934
2826     3942         28   1.447158    1.285714    1.239796
2827     3943         96   1.982271    1.565680    1.549371
2828     3946        100   2.000000    1.164040    1.152400
2829     3947         55   1.740363    1.402020    1.376529
2830     3948        862   2.935507    1.028594    1.027401
2831     3949        304   2.482874    1.019704    1.016350
2832     3950         54   1.732394    1.094340    1.074074
2833     3951         40   1.602060    1.117949    1.090000
2834     3952        388   2.588832    0.874364    0.872110

[2835 rows x 5 columns]

In [148]:
initial_seed.isna().any()

movieid       False
frequency     False
log_value     False
variance_1    False
variance_2    False
dtype: bool

In [149]:
initial_seed['new_score_1'] = initial_seed.log_value * initial_seed.variance_1

In [150]:
initial_seed['new_score_2'] = initial_seed.log_value * initial_seed.variance_2

In [151]:
initial_seed

,movieid,frequency,log_value,variance_1,variance_2,new_score_1,new_score_2
0,1,2077,3.317436,0.726499,0.726149,2.410114,2.408954
1,2,701,2.845718,0.966627,0.965248,2.750749,2.746825
2,3,478,2.679428,1.148566,1.146163,3.077500,3.071062
3,4,170,2.230449,1.026940,1.020900,2.290538,2.277065
4,5,296,2.471292,1.050802,1.047252,2.596837,2.588064
5,6,940,2.973128,0.873455,0.872526,2.596894,2.594131
6,7,458,2.660865,0.960240,0.958143,2.555070,2.549491
7,9,102,2.008600,1.098913,1.088139,2.207277,2.185637
8,10,888,2.948413,0.794296,0.793402,2.341913,2.339275
9,11,1033,3.014100,0.747171,0.746448,2.252048,2.249868
10,12,160,2.204120,1.452673,1.443594,3.201865,3.181854
11,13,99,1.995635,1.113997,1.102745,2.223132,2.200676
12,14,153,2.184691,0.762986,0.757999,1.666889,1.655994
13,15,146,2.164353,1.491403,1.481188,3.227922,3.205813
14,16,682,2.833784,0.819161,0.817960,2.321327,2.317923
15,17,835,2.921686,0.818185,0.817205,2.390481,2.387618
16,18,157,2.195900,1.032745,1.026167,2.267805,2.253361
17,19,389,2.589950,1.389447,1.385875,3.598597,3.589347
18,20,160,2.204120,0.816195,0.811094,1.798992,1.787748
19,21,1356,3.132260,0.873938,0.873293,2.737400,2.735382
20,22,378,2.577492,0.954655,0.952129,2.460614,2.454105
21,23,126,2.100371,1.003429,0.995465,2.107572,2.090845
22,24,624,2.795185,1.139482,1.137656,3.185063,3.179959
23,25,980,2.991226,1.195760,1.194540,3.576788,3.573139
24,26,100,2.000000,0.898081,0.889100,1.796162,1.778200
25,27,61,1.785330,0.962295,0.946520,1.718014,1.689850
26,28,179,2.252853,0.760906,0.756656,1.714210,1.704634
27,29,403,2.605305,0.993655,0.991189,2.588773,2.582349
28,30,74,1.869232,1.025546,1.011687,1.916983,1.891078
29,31,141,2.149219,0.929889,0.923294,1.998534,1.984360
...,...,...,...,...,...,...,...
2805,3914,70,1.845098,1.383230,1.363469,2.552195,2.515735
2806,3915,127,2.103804,1.489939,1.478207,3.134539,3.109857
2807,3916,437,2.640481,0.982817,0.980568,2.595109,2.589170
2808,3917,279,2.445604,1.545164,1.539626,3.778859,3.765315
2809,3918,167,2.222716,1.279994,1.272330,2.845064,2.828028
2810,3919,87,1.939519,0.993050,0.981636,1.926040,1.903901
2811,3920,66,1.819544,1.223543,1.205005,2.226290,2.192559
2812,3923,104,2.017033,0.964899,0.955621,1.946234,1.927520
2813,3925,124,2.093422,1.019407,1.011186,2.134049,2.116839
2814,3926,180,2.255273,0.656580,0.652932,1.480766,1.472540
2815,3927,348,2.541579,0.676505,0.674561,1.719390,1.714449
2816,3928,206,2.313867,1.155127,1.149519,2.672810,2.659835
2817,3929,147,2.167317,0.938310,0.931927,2.033615,2.019780
2818,3930,223,2.348305,1.164101,1.158881,2.733665,2.721406
2819,3932,232,2.365488,0.829004,0.825431,1.961000,1.952547
2820,3933,16,1.204120,1.533333,1.437500,1.846317,1.730922
2821,3936,112,2.049218,0.742519,0.735890,1.521584,1.507998
2822,3937,135,2.130334,0.727805,0.722414,1.550468,1.538984
2823,3938,27,1.431364,1.148148,1.105624,1.643418,1.582550
2824,3939,26,1.414973,1.718462,1.652367,2.431577,2.338055
2825,3941,22,1.342423,1.569264,1.497934,2.106616,2.010860
2826,3942,28,1.447158,1.285714,1.239796,1.860632,1.794181
2827,3943,96,1.982271,1.565680,1.549371,3.103602,3.071273
2828,3946,100,2.000000,1.164040,1.152400,2.328081,2.304800
2829,3947,55,1.740363,1.402020,1.376529,2.440024,2.395660
2830,3948,862,2.935507,1.028594,1.027401,3.019445,3.015943
2831,3949,304,2.482874,1.019704,1.016350,2.531797,2.523469
2832,3950,54,1.732394,1.094340,1.074074,1.895827,1.860719
2833,3951,40,1.602060,1.117949,1.090000,1.791021,1.746245
2834,3952,388,2.588832,0.874364,0.872110,2.263581,2.257747

In [152]:
top_40_variance_1 = initial_seed.sort_values('new_score_1', ascending = False).head(40)

In [153]:
top_40_variance_1

,movieid,frequency,log_value,variance_1,variance_2,new_score_1,new_score_2
1929,2710,1237,3.092370,1.732824,1.731423,5.358532,5.354200
1301,1924,249,2.396199,2.119931,2.111418,5.079778,5.059377
169,231,660,2.819544,1.745921,1.743276,4.922702,4.915243
1895,2657,1233,3.090963,1.588047,1.586759,4.908594,4.904613
213,288,700,2.845098,1.708766,1.706324,4.861606,4.854660
1923,2700,1269,3.103462,1.526163,1.524960,4.736387,4.732655
1930,2712,945,2.975432,1.586651,1.584972,4.720973,4.715977
1163,1676,1163,3.065580,1.447799,1.446554,4.438343,4.434526
1295,1917,1110,3.045323,1.448266,1.446961,4.410438,4.406464
1190,1721,1546,3.189209,1.362936,1.362054,4.346688,4.343877
1722,2427,803,2.904716,1.476905,1.475066,4.289990,4.284648
984,1391,1074,3.031004,1.405722,1.404413,4.260750,4.256783
1870,2628,2250,3.352183,1.267312,1.266749,4.248261,4.246373
1752,2459,247,2.392697,1.775419,1.768231,4.248039,4.230841
808,1183,989,2.995196,1.406221,1.404800,4.211909,4.207651
1912,2683,1434,3.156549,1.324946,1.324022,4.182258,4.179341
2713,3785,613,2.787460,1.498235,1.495791,4.176272,4.169459
1684,2384,523,2.718502,1.536061,1.533124,4.175786,4.167801
241,327,358,2.553883,1.632506,1.627945,4.169228,4.157582
2574,3608,861,2.935003,1.406437,1.404803,4.127896,4.123101
58,70,914,2.960946,1.389515,1.387994,4.114278,4.109777
1087,1573,1421,3.152594,1.291097,1.290189,4.070306,4.067441
1774,2483,25,1.397940,2.910000,2.793600,4.068005,3.905285
1393,2021,789,2.897077,1.399648,1.397874,4.054888,4.049749
2169,3033,899,2.953760,1.372683,1.371156,4.054577,4.050067
2771,3864,143,2.155336,1.862405,1.849381,4.014109,3.986038
2255,3156,383,2.583199,1.551351,1.547301,4.007449,3.996985
158,216,355,2.550228,1.562425,1.558024,3.984542,3.973317
545,780,1730,3.238046,1.227480,1.226770,3.974636,3.972339
2524,3535,630,2.799341,1.417761,1.415510,3.968795,3.962495
862,1241,70,1.845098,2.145963,2.115306,3.959512,3.902947
1726,2431,474,2.675778,1.471642,1.468537,3.937787,3.929479
1577,2253,440,2.643453,1.485691,1.482314,3.927353,3.918427
2125,2976,557,2.745855,1.430085,1.427518,3.926807,3.919757
2259,3160,1113,3.046495,1.281915,1.280763,3.905348,3.901840
1856,2606,207,2.315970,1.685943,1.677799,3.904595,3.885732
1638,2335,420,2.623249,1.486186,1.482647,3.898636,3.889354
755,1088,687,2.836957,1.366384,1.364395,3.876371,3.870729
408,532,389,2.589950,1.495031,1.491188,3.872055,3.862101
2587,3623,1313,3.118265,1.235287,1.234346,3.851951,3.849017

In [154]:
top_40_variance_1 = pd.merge(top_40_variance_1,movielens_1M_final_dataset, on = 'movieid')

In [155]:
#Top 40 movies based on variance_1.

top_40_variance_1

,movieid,frequency,log_value,variance_1,variance_2,new_score_1,new_score_2,title_x,genre_x,imdbId,title_y,genre_y
0,2710,1237,3.092370,1.732824,1.731423,5.358532,5.354200,"Blair Witch Project, The (1999)",Horror,0185937,The Blair Witch Project (1999),Horror
1,1924,249,2.396199,2.119931,2.111418,5.079778,5.059377,Plan 9 from Outer Space (1958),Horror|Sci-Fi,0052077,Plan 9 from Outer Space (1959),Horror|Sci-Fi
2,231,660,2.819544,1.745921,1.743276,4.922702,4.915243,Dumb & Dumber (1994),Comedy,0109686,Dumb &amp; Dumber (1994),Comedy
3,2657,1233,3.090963,1.588047,1.586759,4.908594,4.904613,"Rocky Horror Picture Show, The (1975)",Comedy|Horror|Musical|Sci-Fi,0073629,The Rocky Horror Picture Show (1975),Comedy|Musical
4,288,700,2.845098,1.708766,1.706324,4.861606,4.854660,Natural Born Killers (1994),Action|Thriller,0110632,Natural Born Killers (1994),Crime|Drama
5,2700,1269,3.103462,1.526163,1.524960,4.736387,4.732655,"South Park: Bigger, Longer and Uncut (1999)",Animation|Comedy,0158983,South Park: Bigger Longer & Uncut (1999),Animation|Comedy|Fantasy
6,2712,945,2.975432,1.586651,1.584972,4.720973,4.715977,Eyes Wide Shut (1999),Drama,0120663,Eyes Wide Shut (1999),Drama|Mystery|Thriller
7,1676,1163,3.065580,1.447799,1.446554,4.438343,4.434526,Starship Troopers (1997),Action|Adventure|Sci-Fi|War,0120201,Starship Troopers (1997),Action|Sci-Fi
8,1917,1110,3.045323,1.448266,1.446961,4.410438,4.406464,Armageddon (1998),Action|Adventure|Sci-Fi|Thriller,0120591,Armageddon (1998),Action|Adventure|Sci-Fi
9,1721,1546,3.189209,1.362936,1.362054,4.346688,4.343877,Titanic (1997),Drama|Romance,0120338,Titanic (1997),Drama|Romance
10,2427,803,2.904716,1.476905,1.475066,4.289990,4.284648,"Thin Red Line, The (1998)",Action|Drama|War,0120863,The Thin Red Line (1998),Drama|War
11,1391,1074,3.031004,1.405722,1.404413,4.260750,4.256783,Mars Attacks! (1996),Action|Comedy|Sci-Fi|War,0116996,Mars Attacks! (1996),Comedy|Sci-Fi
12,2628,2250,3.352183,1.267312,1.266749,4.248261,4.246373,Star Wars: Episode I - The Phantom Menace (1999),Action|Adventure|Fantasy|Sci-Fi,0120915,Star Wars: Episode I - The Phantom Menace (1999),Action|Adventure|Fantasy
13,2459,247,2.392697,1.775419,1.768231,4.248039,4.230841,"Texas Chainsaw Massacre, The (1974)",Horror,0072271,The Texas Chain Saw Massacre (1974),Horror
14,1183,989,2.995196,1.406221,1.404800,4.211909,4.207651,"English Patient, The (1996)",Drama|Romance|War,0116209,The English Patient (1996),Drama|Romance|War
15,2683,1434,3.156549,1.324946,1.324022,4.182258,4.179341,Austin Powers: The Spy Who Shagged Me (1999),Comedy,0145660,Austin Powers: The Spy Who Shagged Me (1999),Action|Adventure|Comedy
16,3785,613,2.787460,1.498235,1.495791,4.176272,4.169459,Scary Movie (2000),Comedy|Horror,0175142,Scary Movie (2000),Comedy
17,2384,523,2.718502,1.536061,1.533124,4.175786,4.167801,Babe: Pig in the City (1998),Children's|Comedy,0120595,Babe: Pig in the City (1998),Adventure|Comedy|Drama
18,327,358,2.553883,1.632506,1.627945,4.169228,4.157582,Tank Girl (1995),Action|Comedy|Musical|Sci-Fi,0114614,Tank Girl (1995),Action|Comedy|Sci-Fi
19,3608,861,2.935003,1.406437,1.404803,4.127896,4.123101,Pee-wee's Big Adventure (1985),Comedy,0089791,Pee-wee's Big Adventure (1985),Adventure|Comedy|Family
20,70,914,2.960946,1.389515,1.387994,4.114278,4.109777,From Dusk Till Dawn (1996),Action|Comedy|Crime|Horror|Thriller,0116367,From Dusk Till Dawn (1996),Action|Crime|Fantasy
21,1573,1421,3.152594,1.291097,1.290189,4.070306,4.067441,Face/Off (1997),Action|Sci-Fi|Thriller,0119094,Face/Off (1997),Action|Crime|Sci-Fi
22,2483,25,1.397940,2.910000,2.793600,4.068005,3.905285,"Day of the Beast, The (El D�a de la bestia) (1...",Comedy|Horror|Thriller,0112922,El día de la bestia (1995),Action|Comedy|Crime
23,2021,789,2.897077,1.399648,1.397874,4.054888,4.049749,Dune (1984),Fantasy|Sci-Fi,0087182,Dune (1984),Action|Adventure|Sci-Fi
24,3033,899,2.953760,1.372683,1.371156,4.054577,4.050067,Spaceballs (1987),Comedy|Sci-Fi,0094012,Spaceballs (1987),Adventure|Comedy|Sci-Fi
25,3864,143,2.155336,1.862405,1.849381,4.014109,3.986038,Godzilla 2000 (Gojira ni-sen mireniamu) (1999),Action|Adventure|Sci-Fi,0188640,Gojira ni-sen mireniamu (1999),Action|Adventure|Drama
26,3156,383,2.583199,1.551351,1.547301,4.007449,3.996985,Bicentennial Man (1999),Comedy|Drama|Sci-Fi,0182789,Bicentennial Man (1999),Comedy|Drama|Fantasy
27,216,355,2.550228,1.562425,1.558024,3.984542,3.973317,Billy Madison (1995),Comedy,0112508,Billy Madison (1995),Comedy
28,780,1730,3.238046,1.227480,1.226770,3.974636,3.972339,Independence Day (ID4) (1996),Action|Sci-Fi|War,0116629,Independence Day (1996),Action|Adventure|Sci-Fi
29,3535,630,2.799341,1.417761,1.415510,3.968795,3.962495,American Psycho (2000),Comedy|Horror|Thriller,0144084,American Psycho (2000),Drama
30,1241,70,1.845098,2.145963,2.115306,3.959512,3.902947,Braindead (1992),Comedy|Horror,0103873,Braindead (1992),Comedy|Fantasy|Horror
31,2431,474,2.675778,1.471642,1.468537,3.937787,3.929479,Patch Adams (1998),Comedy|Drama,0129290,Patch Adams (1998),Biography|Comedy|Drama
32,2253,440,2.643453,1.485691,1.482314,3.927353,3.918427,Toys (1992),Action|Comedy|Fantasy,0105629,Toys (1992),Comedy|Drama|Family
33,2976,557,2.745855,1.430085,1.427518,3.926807,3.919757,Bringing Out the Dead (1999),Drama|Horror,0163988,Bringing Out the Dead (1999),Drama|Thriller
34,3160,1113,3.046495,1.281915,1.280763,3.905348,3.901840,Magnolia (1999),Drama,0175880,Magnolia (1999),Drama
35,2606,207,2.315970,1.685943,1.677799,3.904595,3.885732,Idle Hands (1999),Comedy|Horror,0138510,Idle Hands (1999),Comedy|Horror|Thriller
36,2335,420,2.623249,1.486186,1.482647,3.898636,3.889354,"Waterboy, The (1998)",Comedy,0120484,The Waterboy (1998),Comedy|Sport
37,1088,687,2.836957,1.366384,1.364395,3.876371,3.870729,Dirty Dancing (1987),Musical|Romance,0092890,Dirty Dancing (1987),Drama|Music|Romance
38,532,389,2.589950,1.495031,1.491188,3.872055,3.862101,Serial Mom (1994),Comedy|Crime|Horror,0111127,Serial Mom (1994),Comedy|Crime|Thriller
39,3623,1313,3.118265,1.235287,1.234346,3.851951,3.849017,Mission: Impossible 2 (2000),Action|Thriller,0120755,Mission: Impossible II (2000),Action|Adventure|Thriller

In [157]:
top_40_variance_1.to_csv('/home/ishu/Master_Thesis/Data_Comparison/initial_seed_files/initial_seed_variance_1.csv')

In [158]:
top_40_variance_2 = initial_seed.sort_values('new_score_2', ascending = False).head(40)

In [159]:
top_40_variance_2

,movieid,frequency,log_value,variance_1,variance_2,new_score_1,new_score_2
1929,2710,1237,3.092370,1.732824,1.731423,5.358532,5.354200
1301,1924,249,2.396199,2.119931,2.111418,5.079778,5.059377
169,231,660,2.819544,1.745921,1.743276,4.922702,4.915243
1895,2657,1233,3.090963,1.588047,1.586759,4.908594,4.904613
213,288,700,2.845098,1.708766,1.706324,4.861606,4.854660
1923,2700,1269,3.103462,1.526163,1.524960,4.736387,4.732655
1930,2712,945,2.975432,1.586651,1.584972,4.720973,4.715977
1163,1676,1163,3.065580,1.447799,1.446554,4.438343,4.434526
1295,1917,1110,3.045323,1.448266,1.446961,4.410438,4.406464
1190,1721,1546,3.189209,1.362936,1.362054,4.346688,4.343877
1722,2427,803,2.904716,1.476905,1.475066,4.289990,4.284648
984,1391,1074,3.031004,1.405722,1.404413,4.260750,4.256783
1870,2628,2250,3.352183,1.267312,1.266749,4.248261,4.246373
1752,2459,247,2.392697,1.775419,1.768231,4.248039,4.230841
808,1183,989,2.995196,1.406221,1.404800,4.211909,4.207651
1912,2683,1434,3.156549,1.324946,1.324022,4.182258,4.179341
2713,3785,613,2.787460,1.498235,1.495791,4.176272,4.169459
1684,2384,523,2.718502,1.536061,1.533124,4.175786,4.167801
241,327,358,2.553883,1.632506,1.627945,4.169228,4.157582
2574,3608,861,2.935003,1.406437,1.404803,4.127896,4.123101
58,70,914,2.960946,1.389515,1.387994,4.114278,4.109777
1087,1573,1421,3.152594,1.291097,1.290189,4.070306,4.067441
2169,3033,899,2.953760,1.372683,1.371156,4.054577,4.050067
1393,2021,789,2.897077,1.399648,1.397874,4.054888,4.049749
2255,3156,383,2.583199,1.551351,1.547301,4.007449,3.996985
2771,3864,143,2.155336,1.862405,1.849381,4.014109,3.986038
158,216,355,2.550228,1.562425,1.558024,3.984542,3.973317
545,780,1730,3.238046,1.227480,1.226770,3.974636,3.972339
2524,3535,630,2.799341,1.417761,1.415510,3.968795,3.962495
1726,2431,474,2.675778,1.471642,1.468537,3.937787,3.929479
2125,2976,557,2.745855,1.430085,1.427518,3.926807,3.919757
1577,2253,440,2.643453,1.485691,1.482314,3.927353,3.918427
1774,2483,25,1.397940,2.910000,2.793600,4.068005,3.905285
862,1241,70,1.845098,2.145963,2.115306,3.959512,3.902947
2259,3160,1113,3.046495,1.281915,1.280763,3.905348,3.901840
1638,2335,420,2.623249,1.486186,1.482647,3.898636,3.889354
1856,2606,207,2.315970,1.685943,1.677799,3.904595,3.885732
755,1088,687,2.836957,1.366384,1.364395,3.876371,3.870729
408,532,389,2.589950,1.495031,1.491188,3.872055,3.862101
2587,3623,1313,3.118265,1.235287,1.234346,3.851951,3.849017

In [160]:
top_40_variance_2 = pd.merge(top_40_variance_2,movielens_1M_final_dataset, on = 'movieid')

In [161]:
#Top 40 movies based on variance_2.

top_40_variance_2

,movieid,frequency,log_value,variance_1,variance_2,new_score_1,new_score_2,title_x,genre_x,imdbId,title_y,genre_y
0,2710,1237,3.092370,1.732824,1.731423,5.358532,5.354200,"Blair Witch Project, The (1999)",Horror,0185937,The Blair Witch Project (1999),Horror
1,1924,249,2.396199,2.119931,2.111418,5.079778,5.059377,Plan 9 from Outer Space (1958),Horror|Sci-Fi,0052077,Plan 9 from Outer Space (1959),Horror|Sci-Fi
2,231,660,2.819544,1.745921,1.743276,4.922702,4.915243,Dumb & Dumber (1994),Comedy,0109686,Dumb &amp; Dumber (1994),Comedy
3,2657,1233,3.090963,1.588047,1.586759,4.908594,4.904613,"Rocky Horror Picture Show, The (1975)",Comedy|Horror|Musical|Sci-Fi,0073629,The Rocky Horror Picture Show (1975),Comedy|Musical
4,288,700,2.845098,1.708766,1.706324,4.861606,4.854660,Natural Born Killers (1994),Action|Thriller,0110632,Natural Born Killers (1994),Crime|Drama
5,2700,1269,3.103462,1.526163,1.524960,4.736387,4.732655,"South Park: Bigger, Longer and Uncut (1999)",Animation|Comedy,0158983,South Park: Bigger Longer & Uncut (1999),Animation|Comedy|Fantasy
6,2712,945,2.975432,1.586651,1.584972,4.720973,4.715977,Eyes Wide Shut (1999),Drama,0120663,Eyes Wide Shut (1999),Drama|Mystery|Thriller
7,1676,1163,3.065580,1.447799,1.446554,4.438343,4.434526,Starship Troopers (1997),Action|Adventure|Sci-Fi|War,0120201,Starship Troopers (1997),Action|Sci-Fi
8,1917,1110,3.045323,1.448266,1.446961,4.410438,4.406464,Armageddon (1998),Action|Adventure|Sci-Fi|Thriller,0120591,Armageddon (1998),Action|Adventure|Sci-Fi
9,1721,1546,3.189209,1.362936,1.362054,4.346688,4.343877,Titanic (1997),Drama|Romance,0120338,Titanic (1997),Drama|Romance
10,2427,803,2.904716,1.476905,1.475066,4.289990,4.284648,"Thin Red Line, The (1998)",Action|Drama|War,0120863,The Thin Red Line (1998),Drama|War
11,1391,1074,3.031004,1.405722,1.404413,4.260750,4.256783,Mars Attacks! (1996),Action|Comedy|Sci-Fi|War,0116996,Mars Attacks! (1996),Comedy|Sci-Fi
12,2628,2250,3.352183,1.267312,1.266749,4.248261,4.246373,Star Wars: Episode I - The Phantom Menace (1999),Action|Adventure|Fantasy|Sci-Fi,0120915,Star Wars: Episode I - The Phantom Menace (1999),Action|Adventure|Fantasy
13,2459,247,2.392697,1.775419,1.768231,4.248039,4.230841,"Texas Chainsaw Massacre, The (1974)",Horror,0072271,The Texas Chain Saw Massacre (1974),Horror
14,1183,989,2.995196,1.406221,1.404800,4.211909,4.207651,"English Patient, The (1996)",Drama|Romance|War,0116209,The English Patient (1996),Drama|Romance|War
15,2683,1434,3.156549,1.324946,1.324022,4.182258,4.179341,Austin Powers: The Spy Who Shagged Me (1999),Comedy,0145660,Austin Powers: The Spy Who Shagged Me (1999),Action|Adventure|Comedy
16,3785,613,2.787460,1.498235,1.495791,4.176272,4.169459,Scary Movie (2000),Comedy|Horror,0175142,Scary Movie (2000),Comedy
17,2384,523,2.718502,1.536061,1.533124,4.175786,4.167801,Babe: Pig in the City (1998),Children's|Comedy,0120595,Babe: Pig in the City (1998),Adventure|Comedy|Drama
18,327,358,2.553883,1.632506,1.627945,4.169228,4.157582,Tank Girl (1995),Action|Comedy|Musical|Sci-Fi,0114614,Tank Girl (1995),Action|Comedy|Sci-Fi
19,3608,861,2.935003,1.406437,1.404803,4.127896,4.123101,Pee-wee's Big Adventure (1985),Comedy,0089791,Pee-wee's Big Adventure (1985),Adventure|Comedy|Family
20,70,914,2.960946,1.389515,1.387994,4.114278,4.109777,From Dusk Till Dawn (1996),Action|Comedy|Crime|Horror|Thriller,0116367,From Dusk Till Dawn (1996),Action|Crime|Fantasy
21,1573,1421,3.152594,1.291097,1.290189,4.070306,4.067441,Face/Off (1997),Action|Sci-Fi|Thriller,0119094,Face/Off (1997),Action|Crime|Sci-Fi
22,3033,899,2.953760,1.372683,1.371156,4.054577,4.050067,Spaceballs (1987),Comedy|Sci-Fi,0094012,Spaceballs (1987),Adventure|Comedy|Sci-Fi
23,2021,789,2.897077,1.399648,1.397874,4.054888,4.049749,Dune (1984),Fantasy|Sci-Fi,0087182,Dune (1984),Action|Adventure|Sci-Fi
24,3156,383,2.583199,1.551351,1.547301,4.007449,3.996985,Bicentennial Man (1999),Comedy|Drama|Sci-Fi,0182789,Bicentennial Man (1999),Comedy|Drama|Fantasy
25,3864,143,2.155336,1.862405,1.849381,4.014109,3.986038,Godzilla 2000 (Gojira ni-sen mireniamu) (1999),Action|Adventure|Sci-Fi,0188640,Gojira ni-sen mireniamu (1999),Action|Adventure|Drama
26,216,355,2.550228,1.562425,1.558024,3.984542,3.973317,Billy Madison (1995),Comedy,0112508,Billy Madison (1995),Comedy
27,780,1730,3.238046,1.227480,1.226770,3.974636,3.972339,Independence Day (ID4) (1996),Action|Sci-Fi|War,0116629,Independence Day (1996),Action|Adventure|Sci-Fi
28,3535,630,2.799341,1.417761,1.415510,3.968795,3.962495,American Psycho (2000),Comedy|Horror|Thriller,0144084,American Psycho (2000),Drama
29,2431,474,2.675778,1.471642,1.468537,3.937787,3.929479,Patch Adams (1998),Comedy|Drama,0129290,Patch Adams (1998),Biography|Comedy|Drama
30,2976,557,2.745855,1.430085,1.427518,3.926807,3.919757,Bringing Out the Dead (1999),Drama|Horror,0163988,Bringing Out the Dead (1999),Drama|Thriller
31,2253,440,2.643453,1.485691,1.482314,3.927353,3.918427,Toys (1992),Action|Comedy|Fantasy,0105629,Toys (1992),Comedy|Drama|Family
32,2483,25,1.397940,2.910000,2.793600,4.068005,3.905285,"Day of the Beast, The (El D�a de la bestia) (1...",Comedy|Horror|Thriller,0112922,El día de la bestia (1995),Action|Comedy|Crime
33,1241,70,1.845098,2.145963,2.115306,3.959512,3.902947,Braindead (1992),Comedy|Horror,0103873,Braindead (1992),Comedy|Fantasy|Horror
34,3160,1113,3.046495,1.281915,1.280763,3.905348,3.901840,Magnolia (1999),Drama,0175880,Magnolia (1999),Drama
35,2335,420,2.623249,1.486186,1.482647,3.898636,3.889354,"Waterboy, The (1998)",Comedy,0120484,The Waterboy (1998),Comedy|Sport
36,2606,207,2.315970,1.685943,1.677799,3.904595,3.885732,Idle Hands (1999),Comedy|Horror,0138510,Idle Hands (1999),Comedy|Horror|Thriller
37,1088,687,2.836957,1.366384,1.364395,3.876371,3.870729,Dirty Dancing (1987),Musical|Romance,0092890,Dirty Dancing (1987),Drama|Music|Romance
38,532,389,2.589950,1.495031,1.491188,3.872055,3.862101,Serial Mom (1994),Comedy|Crime|Horror,0111127,Serial Mom (1994),Comedy|Crime|Thriller
39,3623,1313,3.118265,1.235287,1.234346,3.851951,3.849017,Mission: Impossible 2 (2000),Action|Thriller,0120755,Mission: Impossible II (2000),Action|Adventure|Thriller

In [162]:
top_40_variance_2.to_csv('/home/ishu/Master_Thesis/Data_Comparison/initial_seed_files/initial_seed_variance_2.csv')